slackhq/nebula

examples/quickstart-vagrant/ansible/roles/nebula/tasks/main.yml

Since nebula-cert does not allow for host.crt or host.key to be overwritten when present, subsequent ansible runs break. This change will have ansible remove previously signed certificates before resigning in the vagrant test environment.

Allow re-signing to work in the vagrant/ansible env

---

examples/config.yaml

Example config didn't have these two options, and they are quite useful, especially for mobile carrier networks.

add hole punching options to example config

---

examples/config.yaml

I was a bit confused by the `-groups` flag on the `nebula-cert ca` command and how to use it (as well as how to rotate the CAs since they expire after a year).
Took me some time (and reading) to connect the dots that the `pki.ca` can contain multiple CAs.
Maybe this a good first hint for others that this possible.

Add note to example about support for multiple CAs

---

cmd/nebula-cert/ca_test.go
cmd/nebula-cert/sign_test.go
cmd/nebula-cert/test_darwin.go

This fixes a couple issues:
- NoSuchFileError not defined for darwin.
- ca_test and sign_test do a bunch of filesystem specific tests that
error differently on Windows. Just disable these tests on Windows for
now.
- Make the signcert test more deterministic by only testing one existing
file at a time.

Fix nebula-cert tests on darwin and windows

---

dns_server.go
examples/config.yml
main.go

This allows configuration of the DNS listener host and port.
I had to move the DNS initialization to a later point in nebula startup to allow the node's nebula IP to be used as DNS bind host, as the interface has to be ready for the bind to succeed in that case. I don't think that should cause any side effects.
I've also added documentation of the config options to the example config. This is backwards-compatible, as it only adds config options. I opted to not move `serve_dns` into `lighthouse.dns.` for that reason.
Common usage scenarios would be changing the port in case another resolver is running on :53, or changing the host to localhost/<nebula node IP> should one not want to publish this on all interfaces.
I have tested this.

Allow configuration of dns listener host/port

---

Makefile
tun_linux.go
udp_linux.go

This patch set adds support for the linux/386 and linux/ppc64le
(GOOS/GOARCH) targets. The 386 target can't currently be built due to
the use of the syscall package and just because there's no
udp_linux_386.go. To fix this, use of the syscall package for Linux has
been replaced with the golang.org/x/sys/unix package (which already had
some sparse use). The latter target, ppc64le, should just require the
udp_linux_ppc64le.go changes, since 386 appears to have the largest
gaps in the syscall package.
Given that the 64 and 32-bit pairs of targets have the same
PrepareRawMessages support, it might be better to push these to use
comment-based build tags instead of filename-based ones.
This patch set is primarily intended to support packaging on Void Linux
(because it supports i686 and …

Add linux-386, linux-ppc64le targets

---

.github/workflows/test.yml

We were building for any commits AND pull requests. This change makes it
so we only build for commits to master AND pull requests.

Fix Github actions duplicate builds

---

udp_linux.go

We were parsing `listen.host`, but not actually using it in the `bind`
call, so we were always binding to `0.0.0.0`.

fix listen.host

---

tun_linux.go

As noted in the comment, the route table should have the MTU set as well. Failing to establish the route is a fatal.
closes #112

Move tun mtu failing to an error log instead of fatal

---

tun_linux.go

Make linux tx queue length an error log instead of a fatal on error

---

.github/workflows/release.yml
Makefile

This script will be triggered by any tag starting with `v` (i.e.
v1.1.0). It will create all of the .tar.gz files (the amd64 binaries will be
compiled on their target systems, the rest of the Linux architecures
will be cross compiled from the Linux amd64 host.)
A SHASUM256.txt will also be generated and attached to the release.

GitHub Action: add release script

---

Makefile

This restores `make bin-windows` and also adds `make
build/nebula-windows-amd64.zip` to build the zip file.

better windows targets in Makefile

---

cmd/nebula-cert/sign.go
cmd/nebula-cert/sign_test.go

`nebula-cert sign` defaults the `--duration` flag to 1 second before the CA expires, so it is not required.
See https://github.com/slackhq/nebula/blob/master/cmd/nebula-cert/sign.go#L102-L104

fix(nebula-cert): flag duration is optional, so reflect this is the cli help

---

main.go

Validate all lighthouse.hosts and static_host_map VPN IPs are in the
subnet defined in our cert. Exit with a fatal error if they are not in
our subnet, as this is an invalid configuration (we will not have the
proper routes set up to communicate with these hosts).
This error case could occur for the following invalid example:
nebula-cert sign -name "lighthouse" -ip "10.0.1.1/24"
nebula-cert sign -name "host" -ip "10.0.2.1/24"
config.yaml:
static_host_map:
"10.0.1.1": ["lighthouse.local:4242"]
lighthouse:
hosts:
- "10.0.1.1"
We will now return a fatal error for this config, since `10.0.1.1` is
not in the host cert's subnet of `10.0.2.1/24`

validate lighthouses and static hosts are in our subnet

---

config.go
examples/config.yml

This change introduces logging.timestamp_format, which allows
configuration of the Logrus TimestampFormat setting. The primary purpose
of this change was to allow logging with millisecond precision. The
default for `text` and `json` formats remains the same for backwards
compatibility.
timestamp format is specified in Go time format, see:
- https://golang.org/pkg/time/#pkg-constants
Default when `format: json`: "2006-01-02T15:04:05Z07:00" (RFC3339)
Default when `format: text`: seconds since beginning of execution
As an example, to log as RFC3339 with millisecond precision, set to:
logging:
timestamp_format: "2006-01-02T15:04:05.000Z07:00"

add logging.timestamp_format config option

---

tun_darwin.go
tun_windows.go

We want to make sure to use the system binaries, and not whatever is in
the PATH.

use absolute paths on darwin and windows

---

connection_manager_test.go
examples/config.yml
handshake_manager.go
handshake_manager_test.go
main.go

This change exposes the current constants we have defined for the handshake
manager as configuration options. This will allow us to test and tweak
with different intervals and wait rotations.
handshakes:
try_interval: 100ms
retries: 20
wait_rotation: 5

add configuration options for HandshakeManager

---

tun_windows.go

Tested on Windows 2019 on AWS.

Support unsafe_routes on Windows

---

config.go

Currently, we require that config file names end with `.yml` or `.yaml`.
This is because if the user points `-config` at a directory of files, we
only want to use the YAML files in that directory.
But this makes it more difficult to use the `-test -config` option
because config management tools might not have an extension on the file
when preparing a new config file. This change makes it so that if you
point `-config file` directly at a file, it uses it no matter what the
extension is.

allow any config file name if specified directly

---

.github/workflows/gofmt.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

This PR does two things:
- Only run the tests when relevant files change.
- Cache the Go Modules directory between runs, so they don't have to redownload everything everytime (go.sum is the cache key). Pretty much straight from the examples: https://github.com/actions/cache/blob/master/examples.md#go---modules

Github Actions: cache modules and only run when necessary

---

firewall.go
firewall_test.go
hostmap.go

A CIDRTree can be expensive to create, so only do it if we need
it. If the remote host only has one IP address and no subnets, just do
an exact IP match instead.
Fixes: #171

only create a CIDRTree for each host if necessary

---

CHANGELOG.md
config.go
connection_manager_test.go
examples/config.yml
lighthouse.go
lighthouse_test.go
main.go
punchy.go
punchy_test.go

Added a delay to punching via lighthouse signal to deal with race conditions in conntrack implementations, which seems to cause issues with random routers. This makes it much more likely that hole punching works.

add configurable punching delay because of race-condition-y conntracks

---

connection_manager.go
handshake_ix.go
handshake_manager.go
hostmap.go
inside.go
outside.go

This change adds a new helper, `(*HostInfo).logger()`, that starts a new
logrus.Entry with `vpnIp` and `certName`. We don't use the helper inside
of handshake_ix though since the certificate has not been attached to
the HostInfo yet.
Fixes: #84

log `certName` alongside `vpnIp`

---

.github/workflows/smoke/smoke.sh
main.go
stats.go

Previously, when using the config test option `-test`, we quit fairly
early in the process and would not catch a variety of additional
parsing errors (such as lighthouse IP addresses, local_range, the new
check to make sure static hosts are in the certificate's subnet, etc).
With this change we skip a few things like creating the tun device, but do as much of the other parsing steps as possible.

Better config test

---

allow_list.go
allow_list_test.go
config.go
config_test.go
examples/config.yml
handshake.go
hostmap.go
lighthouse.go
main.go
outside.go

These settings make it possible to blacklist / whitelist IP addresses
that are used for remote connections.
`lighthouse.remoteAllowList` filters which remote IPs are used when
fetching from the lighthouse (or, if you are the lighthouse, which IPs
you store and forward to querying hosts). By default, any remote IPs are
allowed. You can provide CIDRs here with `true` to allow and `false` to
deny. The most specific CIDR rule applies to each remote.  If all rules
are "allow", the default will be "deny", and vice-versa. If both "allow"
and "deny" rules are present, then you MUST set a rule for "0.0.0.0/0"
as the default.
lighthouse:
remoteAllowList:
"172.16.0.0/12": false
"0.0.0.0/0": true
"10.0.0.0/8": false
"10.42.42.0/24": true
`lighthouse.localAllowList` has the same logic as above, but it …

Add lighthouse.{remoteAllowList,localAllowList}

---

examples/config.yml
handshake.go
main.go
outside.go

This config option should be snake_case, not camelCase.

fix config name for {remote,local}_allow_list

---

hostmap_test.go

This benchmark had an Errorf at the end, lets remove it so the
benchmarks all run.

allow `go test -bench=.` to run

---

examples/config.yml

the rest of the conntrack values match the default

fix typo in conntrack section in examples/config.yml

---

connection_manager_test.go
examples/config.yml
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
inside.go
interface.go
lighthouse.go
lighthouse_test.go
main.go
message_metrics.go
outside.go

This change add more metrics around "meta" (non "message" type packets).
For lighthouse packets, we also record statistics around the specific
lighthouse meta type.
We don't keep statistics for the "message" type so that we don't slow
down the fast path (and you can just look at metrics on the tun
interface to find that information).
These have to be enabled by setting the following in your config:
stats:
message_metrics: true
lighthouse_metrics: true

add meta packet statistics

---

.github/workflows/release.yml
Makefile

This makes GOARM more generic and does GOMIPS in a similar way to
support mips-softfloat. We also set `-ldflags "-s -w"` for
mips-softfloat to give the best chance of the binary working on these
small devices.
Fixes: #201

Build mips-softfloat

---

.github/workflows/smoke.yml
.github/workflows/smoke/build.sh
.github/workflows/smoke/genconfig.sh
.github/workflows/smoke/smoke.sh

Test that basic inbound / outbound firewall rules work during the smoke
test. This change sets an inbound firewall rule on host3, and a new
host4 with outbound firewall rules. It also tests that conntrack allows
packets once the connection has been established.

smoke test: test firewall inbound / outbound

---

tun_linux.go
tun_linux_test.go

If different MTUs are specified for different routes, we should set
advmss on each route because Linux does a poor job of selecting the
default (from ip-route(8)):
advmss NUMBER (Linux 2.3.15+ only)
the MSS ('Maximal Segment Size') to advertise to these destinations when estab‐
lishing TCP connections. If it is not given, Linux uses a default value calcu‐
lated from the first hop device MTU.  (If the path to these destination is asym‐
metric, this guess may be wrong.)
Note that the default value is calculated from the first hop **device
MTU**, not the **route MTU**. In practice this is usually ok as long as the
other side of the tunnel has the MTU configured exactly the same, but we
should probably just set advmss correctly on these routes.
This change goes out of its way to only set …

linux: set advmss correctly when route MTU is used

---

.github/workflows/gofmt.yml
cert/cert.go
cmd/nebula-cert/main_test.go
cmd/nebula-cert/print.go
cmd/nebula-cert/print_test.go
cmd/nebula-cert/verify.go
cmd/nebula-cert/verify_test.go
cmd/nebula-service/main.go
cmd/nebula-service/service.go
cmd/nebula/main.go
config.go
config_test.go
firewall.go
handshake_ix.go
header_test.go
lighthouse_test.go
logger_test.go
main.go
outside.go
outside_test.go
punchy_test.go
ssh.go
sshd/command.go
sshd/server.go
sshd/session.go
stats.go
timeout_test.go
tun_darwin.go

Instead of enforcing `gofmt`, enforce `goimports`, which also asserts a separate section for non-builtin packages. We also skip running the check on *.pb.go files, since they are generated by protoc.

enforce the use of goimports

---

examples/config.yml
handshake_manager.go
handshake_manager_test.go
lighthouse.go
main.go

Currently, we wait until the next timer tick to act on the lighthouse's
reply to our HostQuery. This means we can easily add hundreds of
milliseconds of unnecessary delay to the handshake. To fix this, we
can introduce a channel to trigger an outbound handshake without waiting
for the next timer tick.
A few samples of cold ping time between two hosts that require a
lighthouse lookup:
before (v1.2.0):
time=156 ms
time=252 ms
time=12.6 ms
time=301 ms
time=352 ms
time=49.4 ms
time=150 ms
time=13.5 ms
time=8.24 ms
time=161 ms
time=355 ms
after:
time=3.53 ms
time=3.14 ms
time=3.08 ms
time=3.92 ms
time=7.78 ms
time=3.59 ms
time=3.07 ms
time=3.22 ms
time=3.12 ms
time=3.08 ms
time=8.04 ms
I recommend reviewing this PR by looking at each commit individually, as
some refactoring was required that …

trigger handshakes when lighthouse reply arrives

---

interface.go
tun_android.go
tun_darwin.go
tun_freebsd.go
tun_ios.go
tun_linux.go
tun_windows.go

This commit updates the Interface.Inside type to be a new interface
type instead of a *Tun. This will allow for an inside interface
that does not use a tun device, such as a single-binary client that
can run without elevated privileges.

Make Interface.Inside an interface type

---

firewall.go
firewall_test.go
interface.go

Currently, we drop the conntrack table when firewall rules change during a SIGHUP reload. This means responses to inflight HTTP requests can be dropped, among other issues. This change copies the conntrack table over to the new firewall (it holds the conntrack mutex lock during this process, to be safe).
This change also records which firewall rules hash each conntrack entry used, so that we can re-verify the rules after the new firewall has been loaded. This adds one pointer equality check to the hot path, which I think should be okay.

Preserve conntrack table during firewall rules reload (SIGHUP)

---

handshake_manager.go
inside.go

We are currently triggering a fast handshake for static hosts right
inside HandshakeManager.AddVpnIP, but this can actually trigger before
we have generated the handshake packet to use. Instead, we should be
triggering right after we call ixHandshakeStage0 in getOrHandshake
(which generates the handshake packet)

fix fast handshake trigger for static hosts

---

inside.go

Currently, if a packet arrives on the tun device with a destination that
is not a routable Nebula IP, `queryUnsafeRoute` converts that IP to
0.0.0.0 and we store that packet and try to look up that IP with the
lighthouse. This doesn't make any sense to do, if we get a packet that
is unroutable we should just drop it.
Note, we have a few configurable options like `drop_local_broadcast`
and `drop_multicast` which do this for a few specific types, but since
no packets like this will send correctly I think we should just drop
anything that is unroutable.

drop unroutable packets

---

cert.go
cert/ca.go
cert/cert.go
cert/cert_test.go
examples/config.yml

This PR deprecates the `pki.blacklist` config item and replaces it with `pki.blocklist`.
To support migrations and maintain security, the old config will continue to load for now with warnings being logged.
A future change can complete the deprecation by replacing the warnings with a fatal error.

Use inclusive terminology for cert blocking

---

dist/arch/nebula.service

The provided systemd unit fails to start on systems where the network interface comes up slowly (like wifi) and the lighthouse's `static_host_map` setting uses a domain name rather than an IP address.  This appears to be caused by the network not being up in time to make a DNS lookup.
The proposed changes alter the systemd unit to wait until a network comes up before starting nebula.

Delay starting nebula systemd unit until after a network is up

---

examples/config.yml
main.go
tun_disabled.go

This commit adds support for Nebula to be started without creating
a tun device. A node started in this mode still has a full "control
plane", but no effective "data plane". Its use is suited to a
lighthouse that has no need to partake in the mesh VPN.
Consequently, creation of the tun device is the only reason nebula
neesd to be started with elevated privileged, so this example
lighthouse can also be run as a non-root user.

Support startup without a tun device

---

.github/workflows/gofmt.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

Update all CI checks and release process to use the latest patch version
of go1.15.
Note: We may want to hold off on merge for a week or so just to make sure there are no major issues in the new Go release.

Use Go 1.15

---

udp_linux.go

While attempting to run nebula on an older Synology NAS, it became
apparent that some of the performance optimizations effectively
block support for older kernels. The `recvmmsg` syscall was added in
linux kernel `2.6.33`, and the Synology ds212j (among other models)
is pinned to `2.6.32.12`.
Similarly, `SO_REUSEPORT` was added to the kernel in the 3.9 cycle.
While this option has been backported into _some_ older trees, it
is missing from the Synology kernel.
This commit allows nebula to be run on linux devices with older
kernels if the config options are set up with a single listener
and a UDP listen batch size of 1 (`listen.batch = 1`).

Align linux UDP performance optimizations with configuration

---

ssh.go

Port 22 is blocked as a safety mechanism. In a case where nebula is
started before sshd, a system may be rendered unreachable if nebula
is holding the system ssh port and there is no other connectivity.
This commit enforces the restriction, which could previously be worked
around by listening on an IPv6 address, e.g.  "[::]:22".

Block nebula ssh server from listening on port 22

---

inside.go

```go
3. ==================
WARNING: DATA RACE
Write at 0x00c00030e020 by goroutine 17:
sync/atomic.AddInt64()
runtime/race_amd64.s:276 +0xb
github.com/slackhq/nebula.(*Interface).sendNoMetrics()
github.com/slackhq/nebula/inside.go:226 +0x9c
github.com/slackhq/nebula.(*Interface).send()
github.com/slackhq/nebula/inside.go:214 +0x149
github.com/slackhq/nebula.(*Interface).readOutsidePackets()
github.com/slackhq/nebula/outside.go:94 +0x1213
github.com/slackhq/nebula.(*udpConn).ListenOut()
github.com/slackhq/nebula/udp_generic.go:109 +0x3b5
github.com/slackhq/nebula.(*Interface).listenOut()
github.com/slackhq/nebula/interface.go:147 +0x15e
Previous read at 0x00c00030e020 by goroutine 18:
github.com/slackhq/nebula.(*Interface).consumeInsidePacket()
github.com/slackhq/nebula/inside.go:58 …
```

Fix a data race while sending metrics found in issue #283 case 3

---

CHANGELOG.md
cmd/nebula-service/service.go
go.mod
go.sum

this brings in the new version of kardianos/service which properly outputs logs from launchd services. they added this functionality in 1.1.0, and it makes a change to the launchd plist.

Bring in the new version of kardianos/service and output logfiles on osx

---

examples/service_scripts/nebula.service

During shutdown, this will keep Nebula alive until after sshd is finished. This cleanly terminates ssh clients accessing a server over a Nebula tunnel. h/t @nbrownus 
I tested this on Ubuntu 20.04.1 LTS and Raspbian GNU/Linux 10 (buster).

Added line to systemd config template to start Nebula before sshd

---

handshake_ix.go

Packet 1 is always a stage 1 handshake and packet 2 is always stage 2.
Normal packets don't start flowing until the message counter is 3 or
higher.
Currently we only receive either packet 1 or 2 depending on if
we are the initiator or responder for the handshake, so we end up
marking one of these as "lost". We should instead just always mark
packets 1 and 2 as being seen since a handshake cannot be successful
unless both have been transmitted and received.

don't mark handshake packets as "lost"

---

cert/cert.go
cert/cert_test.go

This fixes a panic in UnmarshalNebulaCertificate when unmarshaling
a payload with Details set to nil.
Fixes: #332

fix panic in UnmarshalNebulaCertificate

---

connection_manager.go
connection_manager_test.go

We were seeing that hosts that have a high number of active hostmap entries show a lot of wasted memory allocations in `HandleMonitorTick()`, so moving these out s.t. we can re-use the allocated memory

Move slice allocations in connection manager monitor loop

---

lighthouse.go
lighthouse_test.go
outside.go
udp_generic.go
udp_linux.go

We noticed that the number of memory allocations `LightHouse.HandleRequest` creates for each call can seriously impact performance for high traffic lighthouses. This PR introduces a benchmark in the first commit and then optimizes memory usage by creating a `LightHouseHandler` struct. This struct allows us to re-use memory between each lighthouse request (one instance per UDP listener go-routine).
Here is the comparison of before and after (`notfound` is that case that a query is made for a non-existent host. `found` is for the case that the host exists):
```
name                                old time/op    new time/op    delta
LighthouseHandleRequest/notfound-4     944ns ±11%     188ns ±15%   -80.07%
LighthouseHandleRequest/found-4       5.53µs ±40%    1.04µs ± 6%   -81.27%
name …
```

Lighthouse handler optimizations

---

connection_manager.go
handshake.go
handshake_ix.go
handshake_manager.go
hostmap.go
outside.go

This change adds an index based on HostInfo.remoteIndexId. This allows
us to use HostMap.QueryReverseIndex without having to loop over all
entries in the map (this can be a bottleneck under high traffic
lighthouses).
Without this patch, a high traffic lighthouse server receiving recv_error
packets and lots of handshakes, cpu pprof trace can look like this:
flat  flat%   sum%        cum   cum%
2000ms 32.26% 32.26%     3040ms 49.03%  github.com/slackhq/nebula.(*HostMap).QueryReverseIndex
870ms 14.03% 46.29%     1060ms 17.10%  runtime.mapiternext
Which shows 50% of total cpu time is being spent in QueryReverseIndex.
This PR also combines a few commonly used together functions like `DeleteVpnIP` / `DeleteIndex` and `AddVpnIPHostInfo` / `AddIndexHostInfo` into one method so that we only have …

add HostMap.RemoteIndexes

---

lighthouse.go

The change introduced by #320 incorrectly re-uses the output buffer for
sending punchBack packets. Since we are currently spawning a new
goroutine for each send here, we need to allocate a new buffer each
time. We can come back and optimize this in the future, but for now we
should fix the regression.

fix regression with LightHouseHandler and punchBack

---

cert/cert.go
cert/cert_test.go

Before this change, if you were to accidentally try to print a file that is not a certificate, you would get a nebulous error message:
`Error: error while unmarshaling cert: proto: can't skip unknown wire type X`
Added the banner check, which results in the clearer error:
`Error: error while unmarshaling cert: bytes did not contain a proper nebula certificate banner`

Check certificate banner during nebula-cert print

---

.github/workflows/gofmt.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml
Makefile

This commit switches to Go 1.16 and adds a release binary for darwin-arm64.
Fixes: #343

Go 1.16 and darwin-arm64

---

examples/config.yml
inside.go
interface.go
main.go
outside.go
tun_android.go
tun_darwin.go
tun_disabled.go
tun_freebsd.go
tun_ios.go
tun_linux.go
tun_windows.go
udp_generic.go
udp_linux.go

This change is for Linux only.
Previously, when running with multiple `tun.routines`, we would only have one file descriptor. This change instead sets IFF_MULTI_QUEUE and opens a file descriptor for each routine. This allows us to process with multiple threads while preventing out of order packet reception issues.
To attempt to distribute the flows across the queues, we try to write to the tun/UDP queue that corresponds with the one we read from. So if we read a packet from tun queue "2", we will write the outgoing encrypted packet to UDP queue "2". Because of the nature of how multi queue works with flows, a given host tunnel will be sticky to a given routine (so if you try to performance benchmark by only using one tunnel between two hosts, you are only going to be using a max of one …

Proper multiqueue support for tun devices

---

main.go
tun_disabled.go

This change allows a server running with `tun.disabled: true` (usually
a lighthouse) to still reply to ICMP Echo Request packets. This allows
you to "ping" the lighthouse Nebula IP as a quick check to make sure the
tunnel is up, even when running with tun.disabled.
This is still gated by allowing `icmp` packets in the inbound firewall
rules.

tun_disabled: reply to ICMP Echo Request

---

cmd/nebula-cert/sign.go
cmd/nebula-cert/sign_test.go
hostmap.go
outside.go

Fix some small grammar mistakes in ``cmd/nebula-cert/sign{,_test}.go`` ``hostmap.go`` and ``outside.go``

fix some small grammar mistakes

---

.github/workflows/smoke.yml
.github/workflows/smoke/Dockerfile
.github/workflows/smoke/build.sh
.github/workflows/smoke/genconfig.sh
.github/workflows/smoke/smoke.sh
Makefile

This makes it easier to use the docker container smoke test that
GitHub actions runs. There is also `make smoke-docker-race` that runs the
smoke test with `-race` enabled.

add `make smoke-docker`

---

handshake_manager.go
hostmap.go
outside.go

We are currently seeing some cases where we are not deleting entries
correctly from the pending hostmap. I believe this is a case of
an inbound timer tick firing and deleting the Hosts map entry for
a newer handshake attempt than intended, thus leaving the Indexes
entry orphaned. This change adds some extra checking when deleteing from
the Indexes and Hosts maps to ensure we clean everything up correctly. With testing, we no longer are seeing a leak with pending hostmap indexes.

More validation in pending hostmap deletes

---

interface.go
udp_generic.go
udp_linux.go

Retrieve the current socket stats using SO_MEMINFO and report them as
metrics gauges. When running with multiqueue, we sum the values
together. If SO_MEMINFO isn't supported, we don't report these metrics.

add metrics for the udp sockets using SO_MEMINFO 

---

firewall.go
firewall_test.go
inside.go
interface.go
main.go
outside.go
udp_generic.go
udp_linux.go

Previously, every packet we see gets a lock on the conntrack table and updates it. When running with multiple routines, this can cause heavy lock contention and limit our ability for the threads to run independently. This change caches reads from the conntrack table for a very short period of time to reduce this lock contention. This cache will currently default to disabled unless you are running with multiple routines, in which case the default cache delay will be 1 second. This means that entries in the conntrack table may be up to 1 second out of date and remain in a routine local cache for up to 1 second longer than the global table.
Instead of calling `time.Now()` for every packet, this cache system relies on a tick thread that updates the current cache "version" each tick. Every …

Routine-local conntrack cache

---

control.go
hostmap.go
inside.go
interface.go
lighthouse.go
main.go

`Rebind` is called by the controlling program when a network interface change is detected (iOS only for now, soon to be others). This code adds a way to signal through the lighthouse that a remote should punch back on a possible new IP for the local, greatly improving the roaming story.
Before this change, roaming on a routable ip generally meant the tunnel would have to die and be stood back up.

Add a way to trigger punch backs via lighthouse

---

Makefile
go.mod

This adds a check to the `Makefile` that informs folks that are trying to build nebula if they are using a version of go that is inappropriate.
I'm no `make` expert but this is working on OSX (gnu make 3.81) and Linux (gnu make 4.3)

Add a check in the makefile to ensure a minimum version of go is installed

---

connection_manager_test.go
connection_state.go
control.go
control_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
inside.go
interface.go
ssh.go

This change fixes all of the known data races that `make smoke-docker-race` finds, except for one.
Most of these races are around the handshake phase for a hostinfo, so we add a RWLock to the hostinfo and Lock during each of the handshake stages.
Some of the other races are around consistently using `atomic` around the `messageCounter` field. To make this harder to mess up, I have renamed the field to `atomicMessageCounter` (I also removed the unnecessary extra pointer deference as we can just point directly to the struct field).
The last remaining data race is around reading `ConnectionInfo.ready`, which is a boolean that is only written to once when the handshake has finished. Due to it being in the hot path for packets and the rare case that this could actually be an issue, holding off …

Fix most known data races

---

main.go

Running a lighthouse with an ephemeral port doesn't make sense, so we should not allow nebula to be started this way.

Do not allow someone to run a nebula lighthouse with an ephemeral port

---

inside.go
outside.go

We missed this race with #396 (and I think this is also the true crash in
issue #226). We need to lock a little higher in the getOrHandshake
method, before we reset hostinfo.ConnectionInfo. Previously, two
routines could enter this section and confuse the handshake process.
This could result in the other side sending a recv_error that also has
a race with setting hostinfo.ConnectionInfo back to nil. So we make sure
to grab the lock in handleRecvError as well.
Neither of these code paths are in the hot path (handling packets
between two hosts over an active tunnel) so there should be no
performance concerns.

fix race in getOrHandshake

---

handshake.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
outside.go

There are some subtle race conditions with the previous handshake_ix implementation, mostly around collisions with localIndexId. This change refactors it so that we have  a "commit" phase during the handshake where we grab the lock for the hostmap and ensure that we have a unique local index before storing it. We also now avoid using the pending hostmap at all for receiving stage1 packets, since we have everything we need to just store the completed handshake.

Refactor handshake_ix

---

handshake_ix.go

The change for #401 incorrectly called HostInfo.ForcePromoteBest in
stage2, when we really we want to pick the remote that we received the
response from.

Fix selection of UDP remote to use during stage2

---

handshake_ix.go
interface.go

This prevents a silly condition noticed in #313 where a host can handshake with itself. 
Notes:
* This is NOT a fix for that issue, and is unlikely to be the cause of the issue, but something we should also stop from happening, because this is a useless entry in the hostMap.
* This will not cleanly merge with #401 and that PR should take precedence. I will update this one once it is merged.
To reproduce this issue you can simply create a `static_host_map` entry pointing a nebula ip besides your own at your local nebula port and initiating traffic to it.
Example:
Host1:
Real IP: 10.1.1.1
Nebula listener port: 1234
Nebula IP: 192.168.1.1
```
static_host_map:
"192.168.1.222": ["10.1.1.1:1234"]
```
```shell
ping 192.168.1.222
(fails)
```
A hostmap entry for yourself will appear and the nebula …

don't allow a useless handshake with yourself

---

lighthouse.go
lighthouse_test.go

Currently, if you use the remote allow list config, as soon as you attempt to create a tunnel to a node that has a blocked IP address, a mutex is locked and never unlocked. This happens even if the node has an allowed remote IP address in addition to the blocked remote IP address.
This pull request ensures that the lighthouse mutex is unlocked whenever we attempt to add a remote IP.

Fix remote allow list lighthouse lock

---

examples/service_scripts/nebula.service

The `StandardError` and `StandardOutput` directives being set to syslog in systemd are obsolete and are no longer [options](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=) and this PR removes them to fix the following gripes in the systemd journal.
```
Mar 18 11:56:05 sts7 systemd[1]: /usr/lib/systemd/system/nebula.service:8: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Mar 18 11:56:05 sts7 systemd[1]: /usr/lib/systemd/system/nebula.service:9: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```

Remove obsolete systemd unit settings.

---

hostmap.go

This check was accidentally typo'd in #396 from `%` to `&`. Restore the
correct functionality here (we want to do the check every "PromoteEvery"
count packets).

fix PromoteEvery check

---

Makefile
control_tester.go
e2e/handshakes_test.go
e2e/helpers_test.go
go.mod
go.sum
tun_android.go
tun_darwin.go
tun_freebsd.go
tun_ios.go
tun_linux.go
tun_linux_test.go
tun_tester.go
udp_tester.go

This change makes it possible to boot multiple `nebula`s in a single process, control their message flow, and gain deep access to their memory.
The initial use case is for robust end to end testing of handshakes.

Start of end to end testing with a good handshake between two nodes

---

.github/workflows/test.yml
Makefile
control.go
control_test.go
control_tester.go
e2e/handshakes_test.go
e2e/helpers_test.go
e2e/router/router.go
handshake_ix.go
hostmap.go
inside.go
ssh.go
tun_tester.go
tun_windows.go
udp_tester.go
udp_windows.go

This test case covers the changes necessary to move beyond a simple case of "I have a bad ip in my hostinfo"
New make targets
- `make e2e` - smallest possible output
- `make e2ev` - include `t.Log` output
- `make e2evv` - include `t.Log` and `logger` `INFO` level output
- `make e2evvv` - include `t.Log` and `logger` `DEBUG` level output
- `make e2evvvv` - include `t.Log` and `logger` `VERBOSE` level output

Simple e2e lies

---

dist/arch/nebula.service
examples/quickstart-vagrant/ansible/roles/nebula/files/systemd.nebula.service

Similar to PR #412, except this removes the remaining references.
`dist/arch/nebula.service` is used by the [Arch `nebula`](https://github.com/archlinux/svntogit-community/blob/packages/nebula/trunk/PKGBUILD#L40) package.

Remove obsolete systemd unit settings (take 2)

---

ssh.go

This will return `null` instead of crashing when running `query-lighthouse` in the ssh server.

Don't panic on a nil response from the lighthouse

---

dns_server.go
main.go

Nebula attempts an Add() call against the global dnsR variable if serveDns is true.
Unfortunately, the global dnsR is only initialized in main.go if the dns config is set to true AND the system is configured to be a lighthouse.
If the host is not configured to be a lighthouse but is also configured to serve DNS, the Add call will panic against the nil dnsR.

Only set serveDns if the host is also configured to be a lighthouse.

---

lighthouse.go

This line has drifted to making it possible to send a failed protobuf packet to the lighthouse while hiding an error log behind a debug check

Fix a failed return in an error case

---

control.go
outside.go
ssh.go

@JohnMaguire noticed that when his mobile device sleeps, and all tunnels are closed (a beta feature), the remote end will try to handshake and enter race avoidance because we haven't properly torn down the tunnels.
To be clear, this only affects mobile clients.

Fully close tunnels when CloseAllTunnels is called

---

outside.go
remote_list.go
udp_all.go

We had a crash in mobile land related to calling `udpAddr.String()` on a nil address, this addresses other possible crashes.

Get out faster on nil udpAddr

---

handshake_ix.go
handshake_manager.go
hostmap.go

We used to check the main hostmap at stage 1 for an existing tunnel and apply race avoidance logic to it. This causes a lot of pain for hosts that were unable to transmit a `close_tunnel` packet but declared the tunnel dead locally (through roaming, unclean shutdown, network loss).
What happens now is that we track the `Time` field transmitted in handshake packet on the hostinfo object, this field has always been present and populated. If we get into the situation described above we will make sure the new handshake is _actually_ newer than the one we used before. If it is, we replace the tunnel. If it wasn't, we enter the same old flow of testing the tunnel. I believe the only real world case here are an incredibly high latency link or an attacker cached a handshake packet and …

Dont apply race avoidance to existing handshakes, use the handshake time to determine who wins

---

firewall.go
handshake_ix.go
handshake_manager.go
hostmap.go
inside.go
interface.go

This change adds the following counter metrics:
Metrics to track packets dropped at the firewall:
firewall.{incoming,outgoing}.dropped.local_ip
firewall.{incoming,outgoing}.dropped.remote_ip
firewall.{incoming,outgoing}.dropped.no_rule
Metrics to track handshakes attempts that have been initiated and ones
that have timed out (ones that have completed are tracked by the
existing "handshakes" histogram).
handshake_manager.initiated
handshake_manager.timed_out
Metrics to track when cached_packets are dropped because we run out of
buffer space, and how many are sent once the handshake completes.
hostinfo.cached_packets.dropped
hostinfo.cached_packets.sent
This change also notes how many cached packets we have when we log the
final "Handshake received" message for either stage1 for stage2.

Add more metrics

---

Makefile
cmd/nebula-service/logs_generic.go
cmd/nebula-service/logs_windows.go
cmd/nebula-service/service.go

This change does the following
- Adjusts the build number for non releases to provide more useful information `$lastReleaseTag-$currentBranch-$commitsAheadOfLastRelease-$currentSha`, if the current directory has uncommitted changes `-dirty` is appended. An example here `1.3.0-win-make-51-gd8fe8ad-dirty` (thanks @wadey for putting this together)
- `Makefile` should work on Windows powershell and command prompt assuming you have `gnu make`, `awk`, `cut`, and `git` installed.
- `make bin` will output binaries with the `.exe` suffix
- Service mode logs are routed to the windows event log system instead of nowhere.
For the `make` dependencies I used `choco` to install `awk`, `make`, and `gnuwin32-coreutils.install`. Also added `%PROGRAMFILES(X86)%\GnuWin32\bin` to `%PATH%`

Minor windows focused improvements

---

.github/workflows/test.yml
handshake_manager.go

There are two cases where you might see a log message "Handshake message
sent" when in actually this did not occur:
1. An error occurred sending the handshake message
2. There were no addresses for consideration when attempting to
handshake
The first case already logs an error. This PR removes the log message in
the second case. It will eventually result in a timeout log.

Remove log when no handshake message is sent

---

handshake_ix.go

#451 introduced a way to more quickly resolve tunnel replacement but the end 2 end tests end up being racy since the current handshake resolution is 1 second and the communication speed there is very fast.
The real world impact of this change is to make tunnel replacement faster on fast networks. Pre v1.4 vs a v1.4 is basically the v1.4 host will always win, even if it shouldn't, but the v1.3 host will always lose in some very specific situations. The fallback mechanism is the same for v1.3 and before, race avoidance.

Increase the timestamp resolution for handshakes

---

inside.go

This is to primarily avoid a deadlock while shutting down but also there's no point in trying to enable faster roaming if we are closing the tunnel.

Don't check for rebind if we are closing the tunnel

---

CHANGELOG.md
ssh.go
sshd/session.go

Before, if you tried to use an ssh client to execute a single command (not on the command line) it would hang as the session would not close properly, this fixes that and adds a way to get a tunnels cert as a PEM.

Fix single command ssh exec, add a `raw` flag to `print-cert`

---

handshake_ix.go

Add `issuer` field to handshake log entries which contains the fingerprint for the issuer of the peer's certificate.  
This change should help in monitoring the replacement of a CA.
Example log entry
```json
{
"certName": "dev2",
"fingerprint": "254b58e5decc72a7c7f5c03b22352ad064a4ea02cfd036d9722cc5ddf8fa8862",
"handshake": {
"stage": 1,
"style": "ix_psk0"
},
"initiatorIndex": 1173343910,
"issuer": "4e700112c26ca67cc64e7b876baad592517778f6a72e03510ed48818d0383cbd",
"level": "info",
"msg": "Handshake message received",
"remoteIndex": 0,
"responderIndex": 0,
"time": "2021-08-10T10:57:49+10:00",
"udpAddr": {
"ip": "127.0.0.1",
"port": 4343
},
"vpnIp": "192.168.100.20"
}
```

Add peer cert issuer to handshake log entries

---

CHANGELOG.md
cert/cert.go
cert/cert_test.go
cmd/nebula-cert/sign.go
cmd/nebula-cert/sign_test.go

`func (nc *NebulaCertificate) VerifyPrivateKey(key []byte) error` would
previously return an error even if passed the correct private key for a
CA certificate `nc`.
That function has been updated to support CA certificates, and
nebula-cert now calls it before signing a new certificate. Previously,
it would perform all constraint checks against the CA certificate
provided, take a SHA256 fingerprint of the provided certificate, insert
it into the new node certificate, and then finally sign it with the
mismatching private key provided.

Check CA cert and key match in nebula-cert sign

---

config.go
connection_manager.go
connection_manager_test.go
control.go
handshake_manager.go
hostmap.go
interface.go
lighthouse.go
main.go
stats.go
tun_darwin.go
tun_freebsd.go
tun_windows.go

This PR makes nebula's Main() method re-callable should it return an error on first invocation.
* Create a context object in nebula.Main, and pass it around to various goroutines, so that they can shut
down on failed Main invocations, as well as when control.Stop() is called.
* Plus cleanup from john@defined.net to ensure Punchy and LhWorker run immediately on startup.

Add a context object in nebula.Main to clean up on error

---

CHANGELOG.md
examples/config.yml
tun_common.go
tun_linux.go
tun_test.go
tun_windows.go

This is needed when using multiple routes to the same destination.
My use case is that I'm connected via OpenVPN and Nebula and both are
using for a default route (kinda HA in case).
```
% grep -A2 0.0.0.0/1 /opt/nebula/config.yml
- route: 0.0.0.0/1
via: 172.16.14.184
metric: 12312321
```
```
% ip route show 0.0.0.0/1
0.0.0.0/1 dev nebula1 scope link metric 12312321 mtu 1300
```
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

Add an ability to specify metric for unsafe routes

---

CHANGELOG.md
lighthouse.go

There is a race between `lhh.HandlerRequest` doing a `lhh.resetMeta` and `lhh.handleHostPunchNotification` when punch back is enabled. This fixes the immediate issue but the note about using a timer wheel still applies.
This also fixes an opportunity for punching back to the wrong host, depending on how many `NebulaMeta_HostPunchNotification` messages a node is receiving.

Fix race between punchback and lighthouse handler reset

---

cmd/nebula-cert/verify_test.go

The most recent test run failed on master: https://github.com/slackhq/nebula/runs/4108898294?check_suite_focus=true
This is because both the CA & node cert are set to a NotAfter of one hour from now. As long as the test executes within the same second, this succeeds. However, if the second boundary elapses between the two cert structs' initialization, the signed cert will have an invalid NotAfter.

Fix flaky test

---

README.md

Formal ECDH in full with acronym.
Missing preposition between groups and hosts.
Hopefully with the preposition it reads better ;-)

docs: improve grammar and readability for README.md

---

.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md

This PR does a few things:
1. Creates universal binaries that work on both `amd64` and `arm64` for darwin.
2. Signs the binaries using key material owned by defined.net
3. Notarizes the resulting zip file using an Apple account owned by defined.net
4. Modernizes the action plugins used in the github release action
This will break existing automations as we no longer publish architecture specific binaries for darwin, only a single `nebula-darwin.zip` will be available going forward.
Interestingly, you still can not execute these binaries in `Finder.app` but it should not complain if you execute them in a terminal.
Closes #24, closes #29

Darwin signing, notarizing, and universal binaries

---

allow_list_test.go
bits_test.go
cert/cert_test.go
cmd/nebula-service/main.go
cmd/nebula/main.go
config/config_test.go
connection_manager_test.go
control_test.go
firewall_test.go
handshake_manager_test.go
lighthouse_test.go
logger.go
main.go
punchy_test.go
test/assert.go
test/logger.go
tun_test.go
util/error.go
util/error_test.go

This is part of a larger restructuring that will give us an `overlay` package containing tun and routing logic

Move util to test, contextual errors to util

---

connection_manager_test.go
control_tester.go
hostmap.go
main.go
overlay/route.go
overlay/tun.go
overlay/tun_android.go
overlay/tun_darwin.go
overlay/tun_disabled.go
overlay/tun_freebsd.go
overlay/tun_ios.go
overlay/tun_linux.go
overlay/tun_linux_test.go
overlay/tun_test.go
overlay/tun_tester.go
overlay/tun_water_windows.go
overlay/tun_windows.go
overlay/tun_wintun_windows.go

Continuation of #576 `main.go` will get further simplified and `Tun` will go away as a public struct in the next one

Move all of tun into overlay

---

wintun/device.go
wintun/tun.go

Without these comments, gofmt 1.16.9 will complain. Since we otherwise
still support building with go1.16.9, lets add the comments to make it
easier to compile.
Related: #588

fix `wintun` package to have // +build comments

---

overlay/route.go
overlay/route_test.go
overlay/tun_wintun_windows.go

tun.RouteFor expects the routeTree to have an iputil.VpnIp inside of it
instead of a *net.IP.
I want to make a test for this as well, but pushing the branch up for now for testing.
Fixes: #594

overlay: fix tun.RouteFor getting *net.IP

---

main.go

When running in `-test` mode, `tun` is set to nil. So we should move the
defer into the `!configTest` if block.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x54855c]
goroutine 1 [running]:
github.com/slackhq/nebula.Main.func3(0x4000135e80, {0x0, 0x0})
github.com/slackhq/nebula/main.go:176 +0x2c
github.com/slackhq/nebula.Main(0x400022e060, 0x1, {0x76faa0, 0x5}, 0x4000230000, 0x0)
github.com/slackhq/nebula/main.go:316 +0x2414
main.main()
github.com/slackhq/nebula/cmd/nebula/main.go:54 +0x540

fix crash with `-test`

---

hostmap.go
outside.go

We might have packets processing in another thread, so we can't safely
just set this to nil. Since we removed it from the hostmaps, the next
packets to process should start the handshake over again.
I believe this comment is outdated or incorrect, since the next
handshake will start over with a new HostInfo, I don't think there is
any way a counter reuse could happen:
> We must null the connectionstate or a counter reuse may happen
Here is a panic we saw that I think is related:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x93a037]
goroutine 59 [running, locked to thread]:
github.com/slackhq/nebula.(*Firewall).Drop(...)
github.com/slackhq/nebula/firewall.go:380 …

don't set ConnectionState to nil

---

cert.go
cert/ca.go
cert/cert_test.go
cert/errors.go
examples/config.yml

Certs can expire while they are in a running config, but nebula will fail to start or to reload config if certs in the PEM are expired at load time.
This PR makes the behaviour more consistent by loading the expired certs into the CA pool (ensuring that host connections with certs issued by the expired CA will log that the CA is expired, rather than missing). We log an error and continue when expired certs exist alongside valid certs, but will hard error and fail to start if there are any other error types or there are only expired certs in the pool.

Allow setup of a CA pool from bytes that contain expired certs

---

CHANGELOG.md

Once merged we can remove the `needs-changelog` tag on the included issues
https://github.com/slackhq/nebula/issues?q=label%3Aneeds-changelog+is%3Aclosed

Update changelog for future 1.5.1 release

---

overlay/route.go
overlay/route_test.go
overlay/tun_darwin.go
overlay/tun_freebsd.go
overlay/tun_linux.go
overlay/tun_tester.go
overlay/tun_water_windows.go
overlay/tun_windows.go
overlay/tun_wintun_windows.go

With the previous implementation, we check if route.MTU is greater than zero,
but it will always be because we set it to the default MTU in
parseUnsafeRoutes. This change leaves it as zero in parseUnsafeRoutes so
it can be examined later.
We also change the behavior to just log a warning if you set an MTU on a route when it isn't supported, instead of making it a fatal error.

fix makeRouteTree allowMTU

---

overlay/tun_darwin.go

With Nebula 1.4.0, if you create an unsafe_route that has a collision with an existing route on the system, the unsafe_route will be silently dropped (and the existing system route remains).
With Nebula 1.5.0, this same situation will cause Nebula to fail to start with an error (EEXIST).
This change restores the Nebula 1.4.0 behavior (but with a WARN log as well).

fix unsafe_route collisions on Darwin

---

overlay/tun_windows.go

`routes` and `unsafeRoutes` were unified back in #581 which broke windows. A warning will be logged as intended with that PR.
https://github.com/slackhq/nebula/blob/b5b9d33ee753b510b316f15b503ecb11209fdf9b/overlay/route.go#L27
Closes #622 
Closes #647

Fix windows unsafe_routes regression

---

lighthouse.go
main.go

Nebula is advertising port '0' to the lighthouse, when configured to dynamically choose a port.
This PR moves the dynamic port discovery code into NewLighthouseFromConfig, to fix the issue.

Make nebula advertise its dynamic port to lighthouses

---

.github/workflows/release.yml
Makefile

Simple change to build for Windows on ARM64 - I did limited testing using my Surface Pro X.

Add to build all windows-arm64 / bin-windows-arm64 build option

---

connection_manager.go

When HandleMonitorTick fires, the hostmap can be nil which causes a panic to occur when trying to clean up the hostmap in handleInvalidCertificate. This fix just stops the invalidation from continuing if the hostmap doesn't exist.

fix panic in handleInvalidCertificate

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

This change does 2 things:
1. When clicking `New Issue` on github, folks will be presented with a set of options. Report a bug, a link to to documentation, and the Slack invite link for the NebulaOSS team.
2. If `File a bug` is selected, folks are presented with a form to fill out.
I will keep the config at [this repo](https://github.com/nbrownus/testing/issues/new/choose) in sync so that we can experiment.
Heavily inspired by [Astro's](https://github.com/withastro/astro/issues/new/choose) setup.

Use issue templates to improve bug reports

---

main.go
ssh.go

The `reload` command sends SIGHUP to the process to let it reload the config, but SIGHUP is not implemented in windows. Rather than indirectly reloading via SIGHUP, this PR explicitly invokes `c.ReloadConfig()` when the `reload` command is given in ssh.
Previous behavior on windows:
```
user@nebula > reload
not supported by windows
```
The new behavior immediately closes the ssh connection once `reload` is given because the sshd server closes, so the user never sees a message, which is probably ok but the ssh handler for `reload` could write a message back to the client just before calling `c.ReloadConfig()`
Resolves https://github.com/slackhq/nebula/issues/694

explicitly reload config from ssh command

---

Makefile
e2e/handshakes_test.go
e2e/helpers_test.go
e2e/router/router.go
inside.go
overlay/tun_tester.go
udp/udp_tester.go

We can use this as a slight approximation of OS independent hot path performance
`make e2e-bench` to get a quick result
A few minor tweaks to reduce allocations during the test

Add a simple benchmark to e2e tests

---

inside.go
outside.go

The intent of this change is to block the processing of packets that may have been sent over an unsafe route.
Host A is an unsafe router serving its local network 172.17.0.0/16 to remote nebula hosts.
Host B is on a remote network, has a nebula ip of 192.168.1.2, and uses 172.17.0.0/16 as an unsafe route.
If Host B uses a relay to connect to Host A OR has `preferred_ranges` set to include `172.17.0.0/16`, it will eventually try to roam the connection to that unsafe route. The result is the Host A receives a packet with a source ip on the nebula network, 192.168.1.2 in this case, which breaks the tunnel since now Host A believes Host B can be sent underlay traffic on the nebula ip and that isn't true.
This change also makes detecting and choosing an unsafe router faster on the overlay …

Refuse to process underlay packets received from overlay ips

---

overlay/tun_android.go

This fixes a hang in Android when shutting down the VPN process.
Per #771 we observed that the Read() call in Interface.listenIn() was blocking even after we called Close() on the underlying file descriptor. This was confusing because the fd was returned to us by the Android system in non-blocking mode and we were able to see that this was true by checking the fd prior to returning in newTunFromFd.
However, the return statement calls `file.Fd()` right after I confirmed that it was in non-blocking mode. @nbrownus discovered that this call has a side effect of setting the fd to blocking mode: https://github.com/golang/go/issues/29277
After removing this call and leaving it in non-blocking mode the shutdown behavior appears to be working correctly.

Fix a hang when shutting down Android

---

connection_manager.go

I don't see these things used anywhere. A most consequential PR.

Remove unused variables from connection manager

---

.github/ISSUE_TEMPLATE/config.yml
README.md

We've created a nebula-specific documentation page at https://docs.defined.net/nebula/, and have improved the config reference docs.  This change links to the new site from the README and the issue template.

Docs: Update doc links

---

examples/config.yml

Fixes #777.
I think aes is the better recommendation anyway given AES hardware acceleration in most devices.

Update config to show aes cipher instead of chacha

---

control.go
handshake_manager.go
outside.go
ssh.go
stats.go

This PR fixes a couple of typos found in the codebase discovered by running `typos .`

Fix typos found by https://github.com/crate-ci/typos

---

.gitignore

I'm not sure what, if anything, created `/cert/*.crt` and `/cert/*.key` but the `**` entries should help avoid accidental commits anywhere in the tree. (I find myself often creating test CAs, certs, etc.)
`make bin-windows` creates `nebula.exe` and `nebula-cert.exe` yet only the former previously appeared in the gitignore.

Add nebula-cert.exe and cert files to .gitignore

---

dns_server.go

Convert hostnames to lowercase during map insertion and lookup.
Fixes #776.
Manually tested...
```
INFO[0000] Starting DNS responder                        dnsListener="0.0.0.0:53"
INFO[0005] Handshake message received                    certName=NoDe1 fingerprint=71544988eed070f0599ce8627918479be60f493b2c729d5abb85fb025e9d0330 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3501997041 issuer=0e1f5f42920c4e24c12496c4
d0f199ecbe0fff92bda4edac352ebd6c2eb7ce84 remoteIndex=0 responderIndex=0 udpAddr="127.0.0.1:58582" vpnIp=192.168.128.2
INFO[0005] Handshake message sent                        certName=NoDe1 fingerprint=71544988eed070f0599ce8627918479be60f493b2c729d5abb85fb025e9d0330 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3501997041 issuer=0e1f5f42920c4e24c12496c4 …
```

Make DNS queries case insensitive

---

firewall_test.go
timeout.go
timeout_system.go
timeout_system_test.go
timeout_test.go

Some configurations can cause a panic when attempting to add an item with `tw.wheelDuration` when `tw.current` is at the final position.
Closes #801

Fix possible panic in the timer wheels

---

connection_manager.go
connection_manager_test.go
firewall.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
inside.go
outside.go
timeout.go

Changes the connection manager to track tunnels based on their local index instead of the vpn ip.
Both `HostMap.Hosts` and `HostMap.Indexes` pointers are still removed, matching the previous behavior. This will enable a future PR to keep the `HostMap.Hosts` pointer in cases where its `hostinfo` does not point to the same local index as `HostMap.Indexes` which means we can do more graceful handshake race resolution.
Depends on #804 which after it merges this branch can be rebased and pointed to `master`

WIP: Track connections by index id instead of vpn ip

---

main.go

Hi! Small change for consistency in structured logging. We have two log calls that emit a `network` field. Currently one of them is a String and the other one is the object itself (which gets encoded as a JSON object for JSON logging). This changes the latter call to emit a String.
Happy to go the other direction, too, if we think that's better, but I'll note that the structure of `Mask` in the resulting log entry is not super great (at least after logstash is done with it):
```json
{"IP": "10.219.11.104", "Mask": "/4AAAA=="}
```

log network as String to match the other log event that emits network

---

inside.go
inside_bsd.go
inside_darwin.go
inside_freebsd.go
inside_generic.go

Fixes #493. This is borrowing the fix from #501 which was originally scoped to use this behavior for all OSes. During review, it was scoped down to just macOS which was known to be affected. Lacking support for FreeBSD at the time was an oversight.
There may be other OSes which are affected by this bug, but we will wait until we get reports to patch them.

Immediately forward packets from self to self on FreeBSD

---

connection_manager.go
connection_manager_test.go
hostmap.go
inside.go
outside.go

Changes the connection manager to track tunnels based on their local index instead of the vpn ip.
Both `HostMap.Hosts` and `HostMap.Indexes` pointers are still removed, matching the previous behavior. This will enable a future PR to keep the `HostMap.Hosts` pointer in cases where its hostinfo does not point to the same local index as `HostMap.Indexes` which means we can do more graceful handshake race resolution.

Track connections by local index id instead of vpn ip

---

control_tester.go
e2e/handshakes_test.go
e2e/router/hostmap.go
e2e/router/router.go
hostmap_tester.go

This is some stuff that is helping me through rehandshaking and wanted to keep it separate from that PR.
e2e tests output mermaid renderings in `e2e/mermaind/${testName}.md` and those would now look like this
```mermaid
sequenceDiagram
participant 10.0.0.2#58;4242 as Nebula: 10.128.0.2<br/>UDP: 10.0.0.2#58;4242
participant 10.0.0.1#58;4242 as Nebula: 10.128.0.1<br/>UDP: 10.0.0.1#58;4242
10.0.0.2#58;4242->>10.0.0.1#58;4242: message(none), index 1034466183, counter: 3
10.0.0.2#58;4242-->>10.0.0.1#58;4242: src port: 90(dnsix)<br/>dest port: 80(http)<br/>data: "Hi from B"
10.0.0.1#58;4242->>10.0.0.2#58;4242: message(none), index 396051440, counter: 4
10.0.0.1#58;4242-->>10.0.0.2#58;4242: src port: 90(dnsix)<br/>dest port: 80(http)<br/>data: "Hello from A"
```
```mermaid
graph TB
subgraph …
```

Render hostmaps as mermaid graphs in e2e tests

---

connection_manager.go
connection_manager_test.go
control.go
e2e/handshakes_test.go
e2e/helpers_test.go
e2e/router/hostmap.go
e2e/router/router.go
go.mod
go.sum
handshake_ix.go
handshake_manager.go
hostmap.go
hostmap_test.go
outside.go
overlay/tun_tester.go
relay_manager.go
ssh.go
udp/udp_tester.go

This change removes handshake race avoidance and allows for multiple tunnels between 2 hosts to exist.
The main drivers for this are
- Enables future re-handshaking PR. We can start a handshake even if there is an existing tunnel to the remote. If the re-handshake succeeds then both tunnels remain active until `ConnectionManager` determines one is no longer in use.
- Allows for rapid recovery in an unclean shutdown, a previous race loser will now get the same benefits as a previous race winner. 
- Opens the possibility for rapid recovery when roaming by detecting the network change and re-handshaking. This is `rebind` on mobile.
`ConnectionManager` will try to guide host pairs that have more than 1 tunnel back to a single tunnel.
The logic is basically:
1. The hostinfo is receiving …

Remove handshake race avoidance

---

examples/service_scripts/nebula.plist

Also using https://launchd.info/ for reference
This adds a `nebula.plist` file to the examples dir which should provide a reasonable example file for someone running nebula on macOS

Add `nebula.plist` based on the homebrew nebula LaunchDaemon plist

---

.github/workflows/smoke/Dockerfile
.github/workflows/smoke/genconfig.sh
.github/workflows/smoke/smoke.sh
examples/config.yml
firewall.go
inside.go
iputil/packet.go
outside.go
overlay/tun_disabled.go

This change allows you to configure the firewall to send REJECT packets
when a packet is denied.
firewall:
outbound_action: drop
inbound_action: drop
These packets are only sent to established tunnels, and only on the
overlay network (currently IPv4 only).
ICMP:
$ ping -c1 192.168.100.3
PING 192.168.100.3 (192.168.100.3) 56(84) bytes of data.
From 192.168.100.3 icmp_seq=2 Destination Port Unreachable
--- 192.168.100.3 ping statistics ---
2 packets transmitted, 0 received, +1 errors, 100% packet loss, time 31ms
TCP:
$ ncat -nzv -w5 192.168.100.2 2000
Ncat: Connection refused.
UDP:
$ ncat -nzuv -w5 192.168.100.3 3000
Ncat: Connected to 192.168.100.3:3000.
Ncat: Connection refused.
This change also modifies the smoke test to capture tcpdump pcaps from
both the inside and outside to inspect …

firewall: add option to send REJECT replies

---

.github/workflows/test.yml
control.go
firewall_test.go

currently `make vet` fails on the repo:
```
./firewall_test.go:140:7: github.com/slackhq/nebula/firewall.Packet composite literal uses unkeyed fields
./firewall_test.go:315:7: github.com/slackhq/nebula/firewall.Packet composite literal uses unkeyed fields
./firewall_test.go:374:7: github.com/slackhq/nebula/firewall.Packet composite literal uses unkeyed fields
./firewall_test.go:460:7: github.com/slackhq/nebula/firewall.Packet composite literal uses unkeyed fields
./control.go:75:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
./control.go:76:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
```
This PR adds a `make vet` step to each of the test jobs. I'll add fixups for the simple go vet errors.

Run `make vet` in CI

---

handshake_manager.go
hostmap.go

@brad-defined and I found multiple hostinfos for a given vpn ip were unlinked inappropriately by the handshake manager.
As part of the spelunking to discover what was unlinking the hostinfos I tripped over some dead code.
Longer term I think we should pull pending hostmap entirely into handshake manager since their needs are quite different anymore.

Remove dead code and re-order transit from pending to main hostmap on stage 2

---

connection_manager.go

Probing a LH isn't actually very useful, since recv_error should catch issues. this avoids stampeding a LH by dropping good tunnels during a reconnect spike.
I debated putting this in connection_manager.go under the `Out` method, but checking there would mean putting `IsLighthouseIP`, which has a lock, into the hot path. Instead, allow these IPs to go into the wheel, but just delete them instead of probing.
We may want to make this behavior optional via config, but I'm inclined to say this is more correct than we we do now, and the old behavior is of dubious value.

remove probes of the lighthouse(s)

---

connection_manager.go
connection_manager_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
interface.go
main.go
outside.go
punchy.go

Similar to #746
This refactors `connectionManager` to drive hole punch maintenance instead of `HostMap`.

Use connection manager to drive NAT maintenance

---

interface.go

This change emits a gauge metric indicating how much time until the certificate expires. The value will go negative once the certificate has expired.
I welcome feedback on the metric name, perhaps `certificate.expiration_seconds` would be better?

emit certificate.expiration_ttl_seconds metric

---

connection_manager.go
connection_manager_test.go

Old connection manager would only track connections with outbound traffic, if there was no inbound then a test packet would be sent to ensure the tunnel was still viable.
This change matches the previous behavior as well as allow for non primary lighthouse tunnels to be torn down eventually

Use fewer test packets

---

handshake_manager.go

The `vpnIps` map I added to `HandshakeManager` in #820 is duplicative of the pending hostmap and was not correctly maintained which caused a handshake to only ever be tried once with a remote vpn ip.
This change reverts that and fixes the regression.

Fix handshake retry regression

---

connection_state.go
inside.go
noiseutil/boring.go
noiseutil/boring_test.go
noiseutil/notboring.go
noiseutil/notboring_test.go

This change only affects builds built using `GOEXPERIMENT=boringcrypto`. When built with this experiment, we use the NewGCMTLS() method exposed by goboring, which validates that the nonce is strictly monotonically increasing. This is the TLS 1.2 specification for nonce generation (which also matches the method used by the Noise Protocol)
- https://github.com/golang/go/blob/go1.19/src/crypto/tls/cipher_suites.go#L520-L522
- https://github.com/golang/go/blob/go1.19/src/crypto/internal/boring/aes.go#L235-L237
- https://github.com/golang/go/blob/go1.19/src/crypto/internal/boring/aes.go#L250
- https://github.com/google/boringssl/blob/ae223d6138807a13006342edfeef32e813246b39/include/openssl/aead.h#L379-L381
- https://github.com/google/boringssl/blob/ae223d6138807a13006342edfeef32e813246b39/crypt …

Use NewGCMTLS (when using experiment boringcrypto)

---

examples/config.yml
main.go
udp/udp_generic.go
udp/udp_linux.go
udp/udp_tester.go

On some networks (like fly.io, DO) it is desirable to listen on specific address and the easiest way to discover that address is by using a known name.
Closes #817

Allow `listen.host` to contain names

---

handshake.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
inside.go
interface.go
lighthouse.go
lighthouse_test.go
outside.go
udp/conn.go
udp/temp.go
udp/udp_generic.go
udp/udp_linux.go
udp/udp_tester.go

Some of the functions called by the udp package need to expose variables whose types are defined in the `nebula` package. Nebula package types can't be imported in the `udp` package without creating an import loop.
* Remove EncWriter from LightHouseHandlerFunc
* Pass the required variables through to lhh.HandleRequest with a wrapper function that uses a closure
* Move EncWriter interface out of udp package, as nothing in udp package references it
* Update EncWriter interface to use real *HostInfo and *Relay objects instead of obfuscating them behind interface{} types
* Also update EncReader similarly, so that non-obfuscated concrete types can be used.

update EncReader and EncWriter interface function args to have concrete types

---

examples/config.yml
overlay/route.go
overlay/route_test.go
overlay/tun_darwin.go
overlay/tun_freebsd.go
overlay/tun_linux.go
overlay/tun_water_windows.go
overlay/tun_wintun_windows.go

This allows informing nebula that it should handle a route but does not establish it on the os routing table. Helpful when doing a full 0.0.0.0/0 unsafe route.
Solves #810

Add ability to skip installing unsafe routes on the os routing table

---

Makefile
boring.go
interface.go
notboring.go
stats.go

This adds a few build targets to compile with `GOEXPERIMENT=boringcrypto`:
- `bin-boringcrypto`
- `release-boringcrypto`
It also adds a field to the intial start up log indicating if boringcrypto is enabled in the binary.

add boringcrypto Makefile targets

---

connection_manager.go
connection_manager_test.go
control_tester.go
e2e/handshakes_test.go
e2e/helpers_test.go
e2e/router/router.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
inside.go
interface.go
lighthouse_test.go
outside.go
punchy.go
relay_manager.go

Nebula can soft-reload its host certificate on a HUP signal. When it reloads a certificate, any new peer tunnels created will use the updated certificate. However, any previously established tunnels will not be updated with this new certificate information.
With this change, Nebula will detect when an older certificate is in use on an existing tunnel, and rebuild the tunnel with the newly updated host certificate. Once hosts have established a new tunnel, packet traversal is migrated to use the new tunnel, and the old tunnel is torn down when its lack of use is detected.
This PR also includes migrating relay information from the previously established tunnel to the new tunnel. A relay established over an older tunnel will be migrated over to the new tunnel, ensuring that the old tunnel …

Rehandshaking

---

connection_manager.go

This is meant to try and reduce what we store in the lighthouse cache with similar behavior to 1.6 and earlier versions of nebula.

Clear lighthouse cache for a vpn ip on a dead connection when its the final hostinfo

---

.github/workflows/test.yml
Makefile
cert/cert.go
noiseutil/boring_test.go
noiseutil/notboring_test.go

ensure we don't have any regressions that go undetected.
for Sign P256: Set the PublicKey field in a more compatible way for the tests. The
current method grabs the public key from the certificate, but the
correct thing to do is to derive it from the private key. Either way
doesn't really matter as I don't think the Sign method actually even
uses the PublicKey field.

add test for GOEXPERIMENT=boringcrypto

---

README.md

Some basic descriptions of P256 and BoringCrypto added to the bottom of README.md so that their purpose is not a mystery.

document P256 and BoringCrypto

---

cidr/tree4.go
cidr/tree4_test.go
examples/config.yml
overlay/tun.go
overlay/tun_android.go
overlay/tun_darwin.go
overlay/tun_freebsd.go
overlay/tun_ios.go
overlay/tun_linux.go
overlay/tun_linux_test.go
overlay/tun_tester.go
overlay/tun_windows.go

Adds a new configuration option that defaults to false. If set to true then `Tun` on linux will use a netlink socket to listen to route table changes on the system.
Example:
```
sudo ip route add 1.1.1.1/32 via 192.168.10.1 dev nebula1
```
`ping 1.1.1.1` would be tunneled through nebula to the host at 192.168.10., which is an unsafe router that is allowed to route the traffic, at which point it exits nebula destined for 1.1.1.1.
This change is similar to #831.
Closes #274

Add ability to respect the system route table for unsafe route on linux

---

examples/config.yml
firewall.go
firewall_test.go

Currently, if a node has unsafe_routes behind it, they can't be firewalled granularly, e.g. opening tcp/443 port will open it for all hosts.
This PR adds new config option, `local_cidr` which is interpreted the same way as `cidr`, but packet's local IP is checked instead of remote IP.
I know that you are not planning to implement general-purpose firewall as per [this comment](https://github.com/slackhq/nebula/issues/142#issuecomment-570250934), however offloading unsafe_route firewalling to iptables will inevitably lose some perks like checking node groups (or require some additional automation to keep them in sync). This commit however does not add any significant performance penalties (local_cidr is checked last, hence it will only impact packets that will be dropped otherwise) and has …

Add destination CIDR checking

---

.github/ISSUE_TEMPLATE/config.yml

This is redundant as Github automatically adds a section for this near the top.

issue templates: remove Report Security Vulnerability

---

cert/cert.go

The private key length is checked in a switch statement below these lines, these lines should have been removed.

fix mismerge of P256 and encrypted private keys

---

cert/ca.go
cert/cert.go
connection_manager.go

CheckSignature and Verify are expensive methods, and certificates are static. Cache the results now that we are calling these methods much more often during the connection_manager runs.

Cache cert verification methods

---

.github/workflows/gofmt.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

This does caching for us, so we can remove our manual caching of modules. Also, we can have it pull the version of Go to use from `go.mod`, so less things to remember in the future.
From the logs, showing that caching is working correctly:
```
Run actions/setup-go@v4
Setup go version spec 1.20
Attempting to resolve the latest version from the manifest...
matching 1.20...
Resolved as '1.20.4'
Found in cache @ /opt/hostedtoolcache/go/1.20.4/x64
Added go to the path
Successfully set up Go version 1.20
/opt/hostedtoolcache/go/1.20.4/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.20.4/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Received 21620006 of 21620006 (100.0%), 93.3 MBs/sec
Cache Size: ~21 MB (21620006 B)
/usr/bin/tar -xf …
```

GitHub actions update setup-go

---

lighthouse.go
lighthouse_test.go
remote_list.go

Only create stop channel when a DNS background goroutine is created. Only send the stop signal when the channel exists.
Also create the channel with a buffer to size 1 so that the stop message can be immediately sent even if the goroutine is busy doing DNS lookups.

Fix reconfig freeze attempting to send to an unbuffered, unread channel

---

.github/workflows/release.yml

actions/create-release is deprecated, just switch to using `gh` cli. This is actually much easier anyways!
test release built with this changeset:
- https://github.com/wadey/nebula/releases/tag/v0.0.1-testrelease4
- https://github.com/wadey/nebula/actions/runs/5190018739/jobs/9356034079

github actions: fix up the release workflow

---

connection_manager_test.go
control_tester.go
handshake_manager.go
handshake_manager_test.go
interface.go
lighthouse.go
main.go
udp/conn.go
udp/udp_android.go
udp/udp_darwin.go
udp/udp_freebsd.go
udp/udp_generic.go
udp/udp_linux.go
udp/udp_linux_32.go
udp/udp_linux_64.go
udp/udp_tester.go
udp/udp_windows.go

This is prep work for windows performance improvements. An interface is needed because we will need to fall back to a different udp `Conn` connection if the windows APIs aren't present.
@rawdigits did some performance testing and did not find any appreciable cost difference.

Use an interface for udp conns

---

Makefile
examples/config.yml
overlay/tun.go
overlay/tun_darwin.go
overlay/tun_freebsd.go
overlay/tun_linux.go
overlay/tun_notwin.go

Fixes #309.
If no name is specified, the system chooses one. If a name _is_ specified, and the tun exists already, we'll try to use it. If it doesn't exist, we'll rename the one the system gives us.
This could've been done with ifconfig, but I figured this was a good start towards syscalls for FreeBSD.

Add support for naming FreeBSD tun devices

---

cmd/nebula/main.go
cmd/nebula/notify_linux.go
cmd/nebula/notify_notlinux.go
dist/arch/nebula.service
dist/fedora/nebula.service
examples/service_scripts/nebula.service

This will send `READY=1` to the unix domain socket described by the `NOTIFY_SOCKET` environment variable, if it was provided, after we have called `Control.Activate()`.
Should resolve timing issues with services that depend on nebulas udp listener(s) and tun device being up.
Closes #921

Attempt to notify systemd of service readiness on linux

---

connection_manager_test.go
control.go
control_test.go
control_tester.go
dns_server.go
handshake.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
hostmap_test.go
inside.go
main.go
outside.go
relay_manager.go
ssh.go

The main `HostMap` has concerns that the pending host map does not and has led to bugs in recent changes.
This change puts `HandshakeManager` in charge of its own dedicated maps that share some similarity with the main `HostMap` but lacks all the extra cruft. This also removes some unused code from the main `HostMap` as a result of the split.
My main concern is: `HandshakeManager.AddVpnIp` will go for a write lock immediately, `Interface.getOrHandshake` won't attempt check the pending hostmap before making a call to this function. This avoids a read lock to write lock trading race that lead to the overcomplication of `Interface.getOrHandshake` long ago. The concern is when restarting nebula on a busy host with many tunnels, there will be a period of strong write lock contention until the …

Pull hostmap and pending hostmap apart, remove unused functions

---

e2e/handshakes_test.go
overlay/tun_tester.go
udp/udp_tester.go

Instead of throwing a panic in a write after close in e2e tests, return an error or fail silently.
In the beginning there was a desire to tightly control packet flow in the e2e tests but as more complicated test cases arose that desire became very difficult to maintain. This led to tests with more automated packet shuffling than originally intended.
As a result some complicated tests can get into a situation where instances had just received a packet when we determine the test complete and close the nebula instance. The instance processing the packet determines it doesn't have a tunnel and tries to send a `recv_error` on the now closed fake udp socket.

Guard e2e tun and udp channels on close

---

Makefile
examples/config.yml
overlay/tun_netbsd.go
udp/udp_netbsd.go

This PR adds (rudimentary) support for NetBSD. NetBSD is very similar to FreeBSD, so only minimal changes to the FreeBSD code were needed to make a functioning NetBSD binary as well. This code has been tested with a DN-generated config and some unsafe_routes and appears to work flawlessly. Glad to help with testing and changes as needed.

Add support for NetBSD

---

.github/workflows/release.yml
Makefile
overlay/tun_netbsd.go
overlay/tun_openbsd.go
udp/udp_bsd.go

Adds a build for `openbsd` and restructures a few things to make supporting bsd family of OS easier.
We should think about this change in relation to #808 
`openbsd` was requested in #806

Build for openbsd

---

control.go
lighthouse.go
lighthouse_test.go
main.go

@JohnMaguire came across this issue today. 
If the `lighthouse.interval` config is changed and nebula reloads it then the reload routine is taken over. This will cause nebula to be unable to shutdown cleanly and block future reloads from occurring.
```
goroutine 11 [select]:
runtime.gopark(0xc0001f56b0?, 0x2?, 0x0?, 0x0?, 0xc0001f567c?)
runtime/proc.go:381 +0xd6 fp=0xc0001f54f8 sp=0xc0001f54d8 pc=0x43b9b6
runtime.selectgo(0xc0001f56b0, 0xc0001f5678, 0xc000191200?, 0x0, 0x0?, 0x1)
runtime/select.go:327 +0x7be fp=0xc0001f5638 sp=0xc0001f54f8 pc=0x44bc5e
github.com/slackhq/nebula.(*LightHouse).LhUpdateWorker(0xc000184a50, {0xd3e608?, 0xc000036fa0}, {0xd3e8e0?, 0xc000191200})
github.com/slackhq/nebula@v1.7.2/lighthouse.go:774 +0x20c fp=0xc0001f56e8 sp=0xc0001f5638 pc=0xa70dac …
```

Send the lh update worker into its own routine instead of taking over the reload routine

---

main.go

These config options are unused, so we should remove the commented code from the project
Ref: https://github.com/DefinedNet/nebula-docs/issues/49

Remove unused config code (last edited 4yrs ago)

---

config/config.go
config/config_test.go
e2e/helpers_test.go
go.mod
go.sum

The mergo package has moved to a vanity URL. This causes fun issues with dependabot. Update to the new release:
- https://github.com/darccio/mergo/releases/tag/v1.0.0
- https://github.com/darccio/mergo/compare/v0.3.15...v1.0.0

update mergo to 1.0.0

---

config/config.go
hostmap.go
interface.go
main.go

Active tunnels cause nebula to re-query the lighthouse every so often, roughly every 5k packets, to make sure we are using the best remote ip address possible for the remote host. On busy tunnels this limit can be hit very quickly and cause unnecessary load on the lighthouses.
This change adds a way to limit the minimum amount of time before the next query is allowed. `timers.requery_wait_seconds` is set to 60 seconds by default and relies on the original counter behavior prior to evaluation. This means an infrequently active tunnel could miss a re-query if the stars align just right.
This also moves the try promote and re-query every counter to config options for a matter of completeness. Initial performance tests look equivalent but I am not opposed to only adding the 1 new config …

Limit how often a busy tunnel can requery the lighthouse

---

connection_manager.go
connection_manager_test.go
connection_state.go
control_tester.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
inside.go
ssh.go

The `ConnectionState` struct doesn't need the entire `CertState` object, this reworks things slightly to make it so we only need to keep track of the local certificate.

Reduce what `HostInfo.ConnectionState` keeps track of

---

connection_manager.go
connection_manager_test.go
connection_state.go
control_tester.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
inside.go
main.go
relay_manager.go
ssh.go

This PR is based on #953. The base branch will be changed to `master` when it merges.
The goal here is to simplify getting a hostinfo and starting a handshake, paving the way to invert how handshake state is tracked so that we don't have to keep all of it around in a fully formed hostinfo.
This should also resolve the last remaining racy issues with interactions between the pending and main hostmap.
There are 2 trouble spots here. 
1. `HandshakeManager.allocateIndex` acquires a main hostmap read lock and a pending hostmap write lock while it holds a hostinfo lock. I haven't found anywhere where that order is violated yet but it's worth some extra eyes.
2. The big lie correction in `handshake_ix.go` is inherently racy, I think it's a little better now than it was before but solving it …

Simplify getting a hostinfo or starting a handshake with one

---

cert/cert.go
cert/crypto.go

This fixes two dropped `err` variables in the `cert` package.

cert: fix dropped errors

---

overlay/tun_wintun_windows.go

Adds a simple retry to create the wintun device if the first time failed.
Closes #982

Retry wintun creation

---

handshake_manager.go

Fixes a regression introduced in #954 
Querying lighthouses for ip information can't be done with the handshake manager lock held since it may cause a handshake to occur with a lighthouse.
Ideally this would happen outside of the hot path but this is the simplest solution for now.

QueryServer needs to be done outside of the lock

---

main.go

This fixes a dropped `err` variable in the `nebula` package

main: fix dropped error

---

.github/workflows/smoke.yml
Makefile

Run the github actions smoke tests with data race detector enabled, so we can detect if a PR introduces a simple data race.
(also fix `make smoke-docker-race` to set CGO_ENABLED correctly)

github actions smoke-test: run with data race detector

---

allow_list.go
allow_list_test.go
calculated_remote.go
cidr/tree4.go
cidr/tree4_test.go
cidr/tree6.go
cidr/tree6_test.go
firewall.go
firewall_test.go
hostmap.go
lighthouse.go
overlay/route.go
overlay/route_test.go
overlay/tun_darwin.go
overlay/tun_freebsd.go
overlay/tun_linux.go
overlay/tun_netbsd.go
overlay/tun_openbsd.go
overlay/tun_tester.go
overlay/tun_water_windows.go
overlay/tun_wintun_windows.go

Had a report in Slack of an issue with `use_system_route_table`. Figured it would be best to make the CIDRTrees safer to use
```
panic: interface conversion: interface {} is *interface {}, not iputil.VpnIp
goroutine 83 [running, locked to thread]:
github.com/slackhq/nebula/overlay.(*tun).RouteFor(0xc000000240?, 0x0?)
github.com/slackhq/nebula/overlay/tun_linux.go:159 +0x85
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000202000, 0xc?, 0xc?)
github.com/slackhq/nebula/inside.go:113 +0x45
github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0xc000202000, {0xc00045d400, 0x3c, 0x2329}, 0xc0000133b0, {0xc0000133c0, 0xc, 0xc}, {0xc00045f900, 0x2329, ...}, ...)
github.com/slackhq/nebula/inside.go:47 +0x22a
github.com/slackhq/nebula.(*Interface).listenIn(0xc000202000, …
```

Use generics for CIDRTrees to avoid casting issues

---

cert/cert_test.go
connection_manager.go
connection_manager_test.go
examples/config.yml
interface.go
main.go

With #838 merged there is a path to refresh certificates and rekey tunnels without having to restart the nebula process. It would be a good practice to flip this to `true`.

Default `pki.disconnect_invalid` to true and make it reloadable

---

header/header.go
inside.go
iputil/packet.go
iputil/packet_test.go
outside.go

We found a few types of packets that could cause a panic here, like if a non-TCP packet has IP header options set. These changes should shore up any edge cases and ensure we reserve the maximum amount of buffer space we need to create the reject packet.

firewall reject packets: cleanup error cases

---

firewall.go
interface.go
main.go

Added a FNV-1 hash of the firewall rules as a Prometheus value.

Added firewall.rules.hash metric

---

config/config.go

Have (*config.C).CatchHUP() return early when there is no file path available from which to reload.
This will allow wrapping service to manage their own signal trapping (which is particularly important if they've used config from a string.

SIGHUP is only useful when config was loaded from a file

---

CHANGELOG.md

Here is an initial pass at a CHANGELOG for 1.8.0 with what has been merged so far.

Prepare CHANGELOG for 1.8.0

---

overlay/tun_android.go
overlay/tun_ios.go

`tun_android.go` and `tun_ios.go` did not get some required updates in 5181cb0474933514c54c52ed41e1ba7e66e50dd4.

Fix mobile builds

---

connection_manager.go
connection_manager_test.go
examples/config.yml
handshake_manager.go
hostmap.go
inside.go
lighthouse.go
ssh.go

@wadey got a deadlock with v1.8.0 and was able to pull the stack trace. `HandshakeManager.GetOrHandshake` can be re-entrant via `HandshakeManager.StartHandshake` through a call to `hm.lightHouse.QueryServer()`. Aside from the double read lock on the main hostmap not being great, the `ConnectionManager` go routine had fired between the 1st and 2nd calls to `HandshakeManager.GetOrHandshake` and was waiting on a write lock for the main hostmap while blocking any future read locks. 
This is fixed by adding a channel and handling the actual lighthouse queries in a go routine. Should also speed up the hot path when many handshakes are occurring.
There is also a case when a tunnel is being tested and is using a relay for a double read lock in `ConnectionManager`.
This is fixed by turning the …

Fix re-entrant `GetOrHandshake` issues

---

.github/workflows/test.yml
Makefile

Ensure that we don't break the build for mobile by doing a `go build` for all of the non-main modules in the repo. Should hopefully catch issues like #1035 sooner.

test: build all non-main modules for mobile

---

README.md

The community repository was merged into extra during the Arch Linux [Git migration](https://archlinux.org/news/git-migration-announcement/) and no longer exists
PS: I've noticed there is a package for nebula in [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=nebula), Wouldn't it be a good idea to add it to the list as well?

Update Arch Linux package link

---

main.go

This used to work correctly when the multiple routines work was first added in #382, but an important part to discover the listen port before opening the other listeners on the same socket was lost in this PR: #653.
This change should fix the regression and allow multiple routines to work correctly when listen.port is set to `0`.
Thanks to @rawdigits for tracking down and discovering this regression.

fix multiple routines when listen.port is zero

---

ssh.go

Make `sshd.host_key` accept inlined key like `pki.ca`.
``` yaml
sshd:
host_key: |
-----BEGIN OPENSSH PRIVATE KEY-----
...
```

Support inlined sshd host key

---

util/error.go

Fix #1068 to provide more information from the `Error()` method of ContextualError objects.
I manually tested to force inject an error and context into Nebula, and printed the error from a client program.
With this change, a full error message is output:
`WARN[2024-01-30T11:43:05-05:00] Failed to initialize Nebula                   error="failed to start nebula: Failed to get a tun/tap device due to manufactured error (map[]): lol wat"`
Without this change, only the underlying error is output:
`WARN[2024-01-30T11:43:30-05:00] Failed to initialize Nebula                   error="failed to start nebula: lol wat"`
I'm on the fence wrt the extra fields.

Return full error context from ContextualError.Error()

---

.github/ISSUE_TEMPLATE/bug-report.yml

Also adds code-fence placeholders and makes these fields required (if logs and config are _truly_ irrelevant, users can write "n/a".)

Add link to logs guide in bug report template

---

cidr/tree4.go
cidr/tree4_test.go
examples/config.yml
firewall.go
firewall_test.go

`local_cidr` was added to firewall rules recently and the current implementation only looks at `local_cidr` if the `host`, `groups`, and `cidr` do not already match. This greatly limits the ability to control what an unsafe router allows for traffic flows.
This change moves `local_cidr` to its own evaluation group that will be checked after doing host identity matching (`host`, `groups`, or `cidr`). If the local certificate has any subnets then all rules will have the local certificates ip address as the `local_cidr` by default to block any unintended exposure via an unsafe route.
This is a breaking change and will require anyone that uses unsafe routes to change their firewall rules to include a `local_cidr` for the traffic they want to allow.

`local_cidr` moved to always be evaluated

---

firewall.go

When `default_local_cidr_any` is set to false, firewall rules that don't include a `local_ip` are treated as though they have a `local_ip` set to the Nebula IP address of the host. This ensures that firewall rules targeting ports on the host don't inadvertently allow traffic to unsafe_routes.
However, the conditional was a big over-eager, and treated explicit `0.0.0.0/0` the same as missing `local_ip`. This was a bug - we want users to be able to create "any" rules explicitly.

Fix "any" firewall rules for unsafe_routes

---

connection_manager.go
connection_manager_test.go
control.go
control_test.go
handshake_ix.go
handshake_manager.go
handshake_manager_test.go
hostmap.go
hostmap_test.go
main.go
ssh.go

This also deprecates the old `local_range` config stanza

Support reloading `preferred_ranges`

---

handshake_manager.go

If the lighthouse queryWorker tries to call StartHandshake on a lighthouse vpnIp, we can deadlock on the handshake_manager lock. This change drops the handshake_manager lock before we send on the lighthouse queryChan (which could block), and also avoids sending to the channel if this is a lighthouse IP itself.
we added this in #996 but removed it in #1044

avoid deadlock in lighthouse queryWorker

---

firewall.go
firewall_test.go
inside.go
outside.go

TCP round trip tracking was an old pet project and never quite worked tright. Recently #1107 showed up and I think the best course of action is to remove the broken feature than try to fix the panic and still have a broken feature.
The firewall should be a tiny bit faster now and consume less memory overall.

Remove tcp rtt tracking from the firewall

---

dns_server.go
dns_server_test.go

Allow `::` in lighthouse.dns.host config

---

ssh.go

I'm not too familiar with pprof, so I didn't realize what file types these commands output, I think it would be helpful to specify as such in the help text for each pprof command that accepts a filename arg.

Add suggested filenames for collected profiles in the ssh commands

---

cmd/nebula-cert/ca.go

elliptic.Marshal was deprecated, we can replace it with the ECDH methods (even though we aren't using ECDH here, the underlying Marshal format is the same). See:
- https://github.com/golang/go/commit/f03fb147d773f3e0cee437e02ac2de5ce1d5e981
We still use `elliptic.Unmarshal` because this issue needs to be resolved first:
- https://github.com/golang/go/issues/63963

switch off deprecated elliptic.Marshal

---

.github/workflows/release.yml

We missed this upgrade in #1047

release: use download-action v4 in docker section

---

CHANGELOG.md
README.md
examples/config.yml

WIP
- https://github.com/slackhq/nebula/pulls?q=is%3Apr+milestone%3Av1.9.0+is%3Aclosed+-label%3Adependencies

prepare CHANGELOG for v1.9.0

---

handshake_manager.go

We had a rare deadlock in GetOrHandshake because we kept the hostmap lock when we do the call to StartHandshake. StartHandshake can block while sending to the lighthouse query worker channel, and that worker needs to be able to grab the hostmap lock to do its work. Other calls for StartHandshake don't hold the hostmap lock so we should be able to drop it here.
This lock was originally added with: https://github.com/slackhq/nebula/pull/954

remove deadlock in GetOrHandshake

---

handshake_ix.go

Ensure we set messageCounter to 2 before the handshake is marked as complete.

ensure messageCounter is set before handshake is complete

---

connection_state.go
handshake_ix.go

Clean up the messageCounter checks added in #1154. Instead of checking that messageCounter is still at 2, just initialize it to 2 and only increment for non-handshake messages. Handshake packets will always be packets 1 and 2.

initialize messageCounter to 2 instead of verifying later

---

udp/udp_linux.go

We had to manually define these types before, but the latest release of `golang.org/x/sys` adds these definitions:
- https://github.com/golang/sys/commit/6dfb94eaa3bd0fcaa615f58e915f7214ce078beb
Since we just updated with this PR, we can clean this up now:
- https://github.com/slackhq/nebula/pull/1161

cleanup SK_MEMINFO vars

---

lighthouse.go
noise.go

This change improves reading of the doc comment after it's been consumed by the Golang LSP:
Before: 
After:

Add puncuation to doc comment

---

.github/workflows/release.yml
.github/workflows/test.yml

macos-11 was deprecated and removed:
> The macos-11 label has been deprecated and will no longer be available after 28 June 2024.
We can just use macos-latest instead.

github actions: use macos-latest

---

overlay/tun_linux.go

Not backwards compatible with IPv4, but it does work
```
47: nebula6: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc fq_codel state UNKNOWN group default qlen 500
link/none
inet6 fd00::1/9 scope global
valid_lft forever preferred_lft forever
inet6 fe80::1745:baed:cd2a:ea73/64 scope link stable-privacy proto kernel_ll
valid_lft forever preferred_lft forever
[jack@jackdesk ~]$ ping -6 fd00::2
PING fd00::2 (fd00::2) 56 data bytes
64 bytes from fd00::2: icmp_seq=1 ttl=64 time=0.721 ms
64 bytes from fd00::2: icmp_seq=2 ttl=64 time=0.622 ms
64 bytes from fd00::2: icmp_seq=3 ttl=64 time=0.612 ms
64 bytes from fd00::2: icmp_seq=4 ttl=64 time=1.46 ms
64 bytes from fd00::2: icmp_seq=5 ttl=64 time=0.648 ms
64 bytes from fd00::2: icmp_seq=6 ttl=64 time=0.636 ms
64 bytes from fd00::2: …
```

make ipv6 address assignment work with tun_linux.go

---

control.go

Adds some hooks to the Control object that expose some lower level Nebula state. Gets a host certificate by IP, attempts to establish a tunnel to a peer, prints tunnel info, and queries a lighthouse.

Make some Nebula state programmatically available via control object

---

handshake_manager.go

A local index collision happens when two tunnels attempt to use the same random int32 index ID. This is a rare chance, and we have code to deal with it, but we have a panic because we return the wrong thing in this case. This change should fix the panic.

fix rare panic when local index collision happens

---

handshake_manager.go
main.go

Fix integer wraparound in the calculation of handshake timeouts on 32-bit targets

---

udp/udp_linux.go

If the host OS is already big endian, we were swapping bytes when we shouldn't have. Use the Go helper to make sure we do the endianness correctly
Fixes: #1189

udp: fix endianness for port

---

examples/go_service/main.go
service/service.go

This allows you to query lighthouse DNS from a gvisor-enabled Nebula application.

Support UDP dialling with gvisor

---

.github/workflows/test.yml
.gitignore
Makefile
cert/cert.go
cmd/nebula-cert/ca.go
cmd/nebula-cert/ca_test.go
cmd/nebula-cert/keygen.go
cmd/nebula-cert/keygen_cgo.go
cmd/nebula-cert/keygen_stub.go
cmd/nebula-cert/keygen_test.go
cmd/nebula-cert/main_test.go
cmd/nebula-cert/p11_cgo.go
cmd/nebula-cert/p11_stub.go
cmd/nebula-cert/sign.go
cmd/nebula-cert/sign_test.go
connection_state.go
go.mod
go.sum
noiseutil/pkcs11.go
pkclient/pkclient.go
pkclient/pkclient_cgo.go
pkclient/pkclient_stub.go
pki.go

Adds PKCS11 support for the P256 curve. It could probably be generalized for curve 25519 as well, but this is what our HSMs support, and therefore what I could easily test.
I've tested _very thoroughly_ against the difficult-to-obtain Microchip TA100, and did a quick verification with a Yubikey 5C.
Here's some quick examples of how this change can be exercised on a TA100. I'll follow up with Yubikey instructions when time permits:
This change requires building with CGO, so here's the exact invocation we used (adjust as needed for your target architecture of course):
```
CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOARCH=arm64 go build -buildvcs=false -ldflags="${LDFLAGS}" -o nebula.arm64.${COMMIT_HASH} ./cmd/nebula
CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOARCH=arm64 go build -buildvcs=false …
```

add PKCS11 support

---

cert/sign.go
cmd/nebula-cert/ca.go
cmd/nebula-cert/sign.go

This can probably also be rebased onto cert-interface, but I haven't tried yet

Add TBSCertificate.SignWith to abstract out sources-of-signatures

---

firewall.go
firewall/packet.go
outside.go
outside_test.go

1. Handle all ICMPv6 traffic with identical rules to ICMP
2. Correct intepretation of port numbers on UDP traffic wrt incoming vs outgoing (I'd like to add a test for this as well, but there's no .Marshal() for IPv6 headers)

Cert V2 firewall fixes

---

cmd/nebula-cert/print.go
cmd/nebula-cert/print_test.go

Before it would print like this:
```
{cert}
{cert}
```
Now it prints like this, so tools that expect json can work with it. This technically breaks the stdout-contract, but so does printing more than one cert:
```
[
{cert},
{cert}
]

fix nebula-cert json printing

---

cert/cert.go
connection_state.go
control.go
handshake_ix.go
interface.go
lighthouse.go
main.go
pki.go
ssh.go

Here's a collection of hacks I've made to get IPv6 connectivity working on networks with:
1. v2-compatible lighthouses with v1 and v2 certs
2. some hosts with just v1 certs, some with both, some with just v2
3. pki.default_version unset on all hosts
Not all of it is good imo, but it does seem to work fairly well.

cert-v2: backwards compatibility trickery for ipv6

---

hostmap.go
inside.go
outside.go
relay_manager.go

Because hosts can have more than one IP now, we need to query the whole list of relay-fors to handle this flow:
1. Host A -> `CreateRelayRequest(HostA, (HostB's non-primary IP))` -> Relay
2. _things happen to set the relay up_
3. Host B -> replies to Host A's handshake via Relay
4. Relay has the following relay-tionships:
- (Host A Primary) -> (Host B secondary)
- (Host B Primary) -> (Host A Primary)
5. in order for this reply to make it back to Host A, we need to look at all the relays on Relay, not just the ones that exactly match the primary address
- Said another way, if you only need to relay to node's primary IPs, this isn't a problem. 
- But, if you only "know" a non-primary IP, you have no way to discover the primary IP without a handshake, which you may need a functional relay to …

cert-v2 relay stuff

---

e2e/handshakes_test.go
handshake_ix.go
remote_list.go

This corrects a situation where you change the overlay address at a static host endpoint.
Starting config:
```yaml
static_host_map:
"192.168.1.1": ["0.0.0.1:4242"]
```
Change the vpn addr serviced at `0.0.0.1:4242` (replaced your lighthouse with a new overlay addr but reused the underlay addr)
```yaml
static_host_map:
"192.168.1.2": ["0.0.0.1:4242"]
```
`nebula` still knows about the first config `"192.168.1.1": ["0.0.0.1:4242"]`. If `nebula` is asked to talk to `192.168.1.1` it will handshake with `0.0.0.1:4242` who is now `192.168.1.2`.
The issue was we were unable to block the underlay addresses provided by the statis host map so nebula would rapidly re handshake with the same bad host.
This also corrects the blocked udp addrs log line and finishes forming the bad tunnel so we can …

Fix static host map wrong responder situations, correct logging

---

e2e/handshakes_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
relay_manager.go

Relays can break and never recover if, with the following setup:
I<->R<->C
the R<->C connection breaks, and the only traffic in the network is I<->C, not C->I.
This change updates host deletion work to mark associated relays as 'Disestablished', because we can't quite tell if they are still working or not. When host `I` finds its relayed connection is in this state, it will now re-send CreateRelayRequest messages to ensure the end-to-end relayed connection.
Relay host behavior was also updated. Before, the Relay host would use the State status of relay peers to immediately return a CreateRelayResponse if the next hop is already in an Established state. This PR changes the Relay to always forward CreateRelayRequest messages along the path, and only terminal relay peers will generate the …

Reestablish relays when last hop fails

---

e2e/handshakes_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
relay_manager.go

Fixes an issue where relays don't re-establish if one hop breaks. 1.9 version of #1270

Backport reestablish relays from cert-v2 to release-1.9

---

README.md

Closes #1306.
Creates a link that will be valid for 10 years/400 people.

Update slack invitation link

---

firewall.go
firewall_test.go
handshake_ix.go
hostmap.go
interface.go

Since we are using `vpnAddrs[0]` as the primary address we need to ensure it's a an address within our own networks.
This came up with a host that was ipv6 only and a host that was both v4/v6. The ipv6 only host would have issues using the v4 hosts primary address for a handful of operations.

Remove unusable networks from remote tunnels at handshake time

---

outside.go
outside_test.go

- Handle both types of header lengths [standard ipv6 and IPSec AH](https://github.com/torvalds/linux/blob/v6.13/include/linux/ipv6.h#L8-L9)
- Deal with fragments in the same way as the ipv4 path (first fragment knows the protocol, 2nd fragment gets marked as a fragment)
- Use fixed error types to avoid the heap allocation on error
- Improves test coverage for `parseV6`
Notably this also removes the header processing limit. The prior limit of 24 was an arbitrary choice and I was unable to determine a defensible limit. Worst case scenario we walk the total size of the packet 8 bytes at a time.
I included a benchmark to show how long a typical packet will take to process and how long a packet with 200 HopByHop headers would take.

Improves ipv6 header parsing

---

allow_list.go
handshake_ix.go
handshake_manager.go
outside.go

This changes the allow list to operate on all known overlay addresses for a remote instead of just the currently used overlay address, when possible.
Since the default is to allow all, any deny is specific intent to not communicate with a remote host on that underlay range, so to reflect that intent we need to evaluate the underlay address against each of the overlay addresses allow list tables.
There is 1 tricky spot with stage 2 handshakes where we could operate on all known addresses but that would pollute our noise state since we have to consume the packet and ratchet the state forward to get a full set of overlay addresses in the remote certificate. Currently this is not being done but we can achieve it if deemed necessary, ideally the remote side has identical configuration that …

Change allow list to evaluate all vpnaddr tables when available

---

.github/workflows/smoke-extra.yml

Ubuntu 24.04 doesn't include vagrant anymore, so add the hashicorp source

smoke-extra: support Ubuntu 24.04

---

.github/workflows/smoke/smoke-vagrant.sh

We can't run the `ncat` tests unless we can make sure to install it to all of the vagrant boxes.
Also clean up the log output by disabling TTY on the `vagrant ssh` calls (with `-T`, see https://github.com/hashicorp/vagrant/issues/11882 )

smoke-test-extra: cleanup ncat references

---

cert/cert.go
handshake_ix.go
handshake_manager.go

Fixes a bug where the cert was not printed in debug log level when an invalid cert is encountered.
Adds some information about an invalid cert when in info log level is set. This is to help locate the offending host/certificate.
Logs the cert in some cases after we have determined it is trusted but still invalid for some reason.

Improve logging when handshaking with an invalid cert

---

.github/workflows/test.yml
.golangci.yaml
allow_list_test.go
calculated_remote_test.go
cert/ca_pool_test.go
cert/cert_v1_test.go
cert/cert_v2_test.go
cert/crypto_test.go
cert/pem_test.go
cert/sign_test.go
cmd/nebula-cert/ca_test.go
cmd/nebula-cert/keygen_test.go
cmd/nebula-cert/main_test.go
cmd/nebula-cert/print_test.go
cmd/nebula-cert/sign_test.go
cmd/nebula-cert/verify_test.go
config/config_test.go
connection_manager_test.go
e2e/handshakes_test.go
firewall_test.go
header/header_test.go
lighthouse_test.go
outside_test.go
overlay/route_test.go
punchy_test.go

Follow-up to #1321 
This fixes one more (kinda big) rule ([`require-error`](https://github.com/Antonboom/testifylint?tab=readme-ov-file#require-error)) that requires using `testify/require` instead of `testify/assert` for assertions having to do with errors, halting execution of the test if the assertion fails.
After that, we can enable linting of `testifylint` in CI w/ everything green. I'm using <https://golangci-lint.run> to run this linter in CI / I've been using it locally as well.

Enable running testifylint in CI

---

examples/config.yml
udp/udp_linux.go

This PR adds the ability to mark the traffic on the nebula interface for linux based systems. This allows the user to handle the nebula generated taffic via ip rules and using generic routing tables. For example, this allows the use of default routes via nebula for clients that already have a default gw set due to their network setup.
Current state:
0.0.0.0/0 routing is already possible in nebula using network namespaces (see https://www.wireguard.com/netns/) however I noticed in my own testing that moving network interfaces between namespaces can often introduce different new problems. E.g. you loose ip assignements on interfaces, `ip a` does not show your physical nic anymore resulting in problems with network managers on desktop style clients.
Related issues / existing pull requests:
- …

add so_mark sockopt support

---

examples/config.yml

The current example config defaults to listening only on IPv4. I think the default config makes sense to be listening on all paths, including IPv6 paths, so I've updated this example config, as well as inverting the comment that explains how to adjust it.

Update example config to listen on `::` by default

---

.github/workflows/gofmt.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

This doesn't change our go.mod, which still only requires go1.22 as a minimum. It only changes our builds to use go1.24 so we have the latest improvements.

build with go1.24

---

handshake_ix.go

This attempts to add the certificate version to logs as an additional field `certVersion` where it makes sense.
I'm not sure I've placed this everywhere it makes sense, and I'm not sure I've used the right data, so please give it a good look.
But I've figured deriving the cert version from the same data as the cert name and adding the logging where certName is added should minimize getting it wrong.
Looking good to me! 👍

Add `certVersion` field to logs when logging the cert name in handshakes

---

overlay/route.go
overlay/route_test.go

We switched to yaml.v3 with #1148, but missed this spot that was still casting into `map[any]any` when yaml.v3 makes it `map[string]any`. Also clean up a few more `interface{}` that were added as we changed them all to `any` with #1148.

fix parseUnsafeRoutes for yaml.v3

---

sshd/session.go

The `golang.org/x/crypto/ssh/terminal` was deprecated and moved to `golang.org/x/term`. We already use the new package in `cmd/nebula-cert`, so fix our remaining reference here.
See:
- https://github.com/golang/go/issues/31044

move to golang.org/x/term

---

config/config.go

---
To fix the problem, we need to ensure that the value being converted to `uint32` is within the valid range for `uint32`, which is from 0 to `math.MaxUint32`. This involves adding a lower bound check to ensure the value is not negative. 
The best way to fix this is to modify the `GetUint32` function to include a check for negative values before performing the conversion. This can be done by adding a condition to check if the value is less than 0 and returning the default value `d` if it is.

Fix: Incorrect conversion between integer types

---

control.go
dns_server.go
firewall.go
handshake_ix.go
handshake_manager.go
hostmap.go
inside.go
interface.go
lighthouse.go
lighthouse_test.go
outside.go
pki.go
relay_manager.go

Use `bart.Lite` and `.Contains` as suggested by the bart maintainer:
- https://github.com/gaissmai/bart/commit/9455952eedcf59a6e755fc28ed16e906fa4f3066#commitcomment-155362580

optimize usage of bart

---

cert/crypto_test.go

Fixes #1387 by re-generating these test keys using the second recommendations, for memory-constrained machines, from the Argon2 RFC (64 MiB, 3 iterations, 4 lanes): https://datatracker.ietf.org/doc/rfc9106/

Support 32-bit machines in crypto test

---

README.md

I made a couple other minor tweaks for consistency (removing superfluous spaces that weren't used for Markdown rendering, fixing spacing between headers, etc.) or readability/clarity but the primary goal here is to avoid surprise CA expiration in the future.

Mention CA expiration in the README

---

README.md

Closes #1388 
This removes the shell prompt from the install snippets, allowing those blocks to be copied and directly pasted into a terminal.
This also adds the `sh` block syntax coloring to all shell snippets.

Minor fixes to Readme shell snippets

---

connection_manager.go

With the move to ipnet.Addr types, there will be a panic if an uninitialized netip.Addr type has `As4()` called on it.
We received a stack trace from a user showing this was happening on line 274 of connection_manager. Based on code inspection, this PR ensures that every State case is covered to avoid an uninitialized Addr panicking on line 274.
I tried for a bit, but couldn't come up with a nice automated test for this case.

Fix relay migration panic by covering every possible relay state

---

udp/udp_rio_windows.go

Fix #1411 
My previous PR #1404  handled some UDP receive errors returned with a limited retry loop, with a counter to suss out whether an error condition was temporary or permanent. I wasn't sure at the time what was causing the UDP receive to return errors.
I can now reproduce errors in this path, by disabling the Windows firewall (or otherwise ensuring ICMP messages are not filtered out on the host) and by sending ICMP Destination Unreachable packets to the Windows host with the Nebula UDP socket port number.
For each ICMP received by Windows, there will be an error returned by the UDP receive call. This means that the `consecutiveErrors` counter can't really be trusted - the errors will be determined by the number of ICMP packets, not by some indeterminate cause.
To resolve this …

Disable UDP receive error returns due to ICMP messages on Windows.

---

connection_manager.go
connection_manager_test.go
control.go
e2e/handshakes_test.go
e2e/router/router.go
e2e/tunnels_test.go
examples/config.yml
handshake_ix.go
hostmap.go
inside.go
interface.go
main.go
outside.go

This PR enables nebula to close tunnels after a period of inactivity, it is not enabled by default but we should enable it in a future major/minor release. It also disables punchy from punching to lighthouses, which comes with some very narrow caveats which are detailed in the comments.
The original PoC is present in #1405 
2 new config items are added, both are reload-able.
- `tunnels.drop_inactive` - Enables or disables the feature, default is disabled (false) currently.
- `tunnels.inactivity_timeout` - Determines the duration of inactivity before `tunnels.drop_inactive` is armed. Default is currently 10 minutes.
This is a rather large refactor because each state we wanted to track became map of all tunnel indexes with their own mutexes, those mutexes have caused problems in the past, …

Drop inactive tunnels

---

control_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
hostmap_test.go

Store relays in a slice for consistent ordering. The first IP placed in the slice will always be the first one returned in the copy.
This will ensure that the first relay established during handshaking is always the relay used to send traffic (unlike the map, which will order the relay ip's arbitrarily, should additional relays be established after the initial setup is complete.) Additionally, golang returns map orderings somewhat randomly. Changing this to an ordered slice ensures that the same relay is always used in a connection.

Store relay states in a slice for consistent ordering

---

udp/errors.go
udp/udp_darwin.go
udp/udp_generic.go
udp/udp_linux.go

Golang stdlib has a situation in darwin where a UDP write can return `EAGAIN` but never sees a writeable event bubble up from `kevent` which causes the write to deadlock, [bug report](https://github.com/golang/go/issues/73919). 
This PR attempts to avoid the deadlock by making our own `sendto` syscall and returning an error when `EAGAIN` is encountered.
The reason I am lifting `sendto` out of the `x/sys` package is because Apple doesn't like folks calling the kernel directly and instead wants them to go through `libSystem` and I would rather not re-implement the trampoline through assembly in our codebase. Doing a direct syscall might also block future releases of mobile nebula.
- https://github.com/golang/go/issues/17490
- https://github.com/golang/go/issues/28984
Side note: Rebind …

Darwin udp fix

---

control_test.go
handshake_ix.go
handshake_manager.go
hostmap.go
hostmap_test.go

port #1422 to master from release-1.9
Use an ordered list of relay IPs for consistent relay use

Use a list for relay IPs instead of a map

---

udp/udp_generic.go
udp/udp_rio_windows.go

Windows is returning errors on UDP_NETRESET ioctls now. This code was inspired by golang stdlib code, and included as a best effort to minimize the number of errors returned by Windows udp receive operations.
When this fails, Nebula falls back to the generic UDP code.
This PR updates the ioctls to quietly log failures and continue processing.
I manually tested this and I do not see errors being returned by the udp receive operation when the Windows host receives icmp unreachable messages.

Quietly log error on UDP_NETRESET ioctl on Windows.

---

overlay/tun_linux.go

Currently we assume each route update must have a destination, but we should check that it is set before we try to use it.
See: #1436

netlink: ignore route updates with no destination

---

connection_manager.go
lighthouse.go
lighthouse_test.go

Don't delete static host mappings for non-primary IPs

---

hostmap.go
outside.go

Since #955 (v1.8.0) we have changed from dropping a tunnel on the 4th `recv_error` receipt to dropping a tunnel on the 1st `recv_error` receipt. This change reverts to the pre-v1.8.0 behavior.
Ultimately, I think it would be best to remove `recv_error` messages entirely and rely on `tunnels.drop_inactive` (which landed in v1.9.6 and `test` packets to sort out tunnel issues). I am submitting this change to v1.9.x in case we do not want to take on that deprecation at this point but would argue that, at worst, we should in v1.10.

Fix `recv_error` receipt limit allowance for v1.9.x

---

lighthouse.go

If we don't use this information, don't put it on the wire, so we then do not have to check it. If this does indeed have a use, we can just remove the comment and close this

don't require a detailsVpnAddr in a HostUpdateNotification

---

overlay/tun.go
overlay/tun_darwin.go
overlay/tun_freebsd.go

This is a continuation of #1399 to finish off the last of the `exec.Command`s in freebsd which is needed for ipv6 unsafe route support

Use x/net/route to manage routes directly
