config.go
=> Better error message when no config files found

main.go
Should help debug situations like #27 and #11 more quickly
=> Improve tun/udp init error messages

examples/config.yaml
=> Fix config comment

examples/config.yaml, handshake.go, handshake_ix.go, interface.go, main.go
remove all of the hmac/support stuff. this should be replaced by psk functions in noise.
=> remove old hmac function. superceded by ix_psk0

lighthouse.go, lighthouse_test.go, main.go
=> Add an error (non fatal) when a lighthouse host has no static entry

Makefile, cmd/nebula-service/main.go, cmd/nebula-service/service.go, go.mod, go.sum
** Work in progress **
Allows the nebula binary to install itself under the standard service manager on many platforms via the github.com/kardianos/service library.
=> make nebula a service that can install itself

cmd/nebula-cert/sign.go
=> Fix impossible error message condition, go fmt

connection_manager_test.go, lighthouse.go, lighthouse_test.go, main.go
=> Fail with a better error message if a lh hosts is unparsable

.github/workflows/test.yml
This allows us to run automated builds and tests for the three OSes.
=> Use Github Actions for Linux, Windows and macOS

.github/workflows/gofmt.yml, cmd/nebula-cert/ca.go, cmd/nebula-cert/ca_test.go, cmd/nebula-cert/keygen_test.go, cmd/nebula-cert/print.go, cmd/nebula-cert/print_test.go, cmd/nebula-cert/sign_test.go, cmd/nebula-cert/verify.go, cmd/nebula-cert/verify_test.go, firewall_test.go, ssh.go
This runs gofmt for all pull requests, to make sure no files need to be reformatted.
Also, run gofmt on all current files so it will pass.
When it fails, it gives a diff of what needs to change. See here for an example of how a failure looks: https://github.com/slackhq/nebula/runs/345051948
=> Add gofmt Github action

examples/config.yml
=> derp- example config is now less silly

README.md
Fixed the wrong node names mentioned
=> Fix for Issue #90

firewall.go, firewall_test.go
=> Detect group array usage and try to be kind

hostmap.go
=> make this a warning, even though i believe it is fundamentally an error (in judgement)

lighthouse.go
=> Allow ValidateLHStaticEntries to check all static host map entries

tun_darwin.go
=> Support unsafe_routes on Darwin

examples/quickstart-vagrant/README.md, examples/quickstart-vagrant/ansible/playbook.yml, examples/quickstart-vagrant/ansible/roles/nebula/tasks/main.yml
Change to the newer target format in Makefile for vagrant builds.
=> conform to new build format for vagrant

CHANGELOG.md
Update the changelog to mark today as the release day for 1.1.0.
=> Prepare for 1.1.0 release.

inside.go
This happens on my osx test box.
=> check that packet isn't bound for my vpn ip

.github/workflows/gofmt.yml, .github/workflows/release.yml, .github/workflows/smoke.yml, .github/workflows/test.yml
- https://golang.org/doc/go1.14
I did a performance sanity check in Docker, and performance seems about
the same (perhaps slightly higher).
=> build and test with go1.14

tun_common.go, tun_test.go
MTU was missing from the route object being returned from `parseUnsafeRoutes`
=> Fix MTU in unsafe_routes

dist/arch/nebula.service, dist/wireshark/nebula.lua
- First cut at a unified wireshark dissector
- Systemd unit for arch in repo
=> Add a systemd unit for arch and a wireshark dissector

tun_android.go, tun_linux.go
This adds a new tun file for android, very similar to linux but we take care of `Activate` before `nebula` boots.
=> Fix up the tun for android

handshake_ix.go
The revocation list is something I'm interested in using but unless the public certificate is recorded on creation its a bit unwieldy. If we were to log the certificate fingerprint on handshakes, this revocation functionality would be more accessible.
=> log remote certificate fingerprint on handshakes

CHANGELOG.md
This includes all public facing changes that have merged since 1.2.0:
https://github.com/slackhq/nebula/milestone/3?closed=1
=> CHANGELOG for 1.3.0

hostmap.go
=> i don't think this is used at all anymore

examples/config.yml
As far as I can tell this isn't listed besides in the source code.
Adding this to assist others.
=> List possible cipher options in example config

dist/fedora/nebula.service
This adds in the dist files for Fedora Linux packages.
=> Fedora Linux package support

main.go, udp_all.go
ipv6 merge broke dns name usage in config as per this comment https://github.com/slackhq/nebula/commit/7073d204a896ee1980a93e263d3100b12b961296#r48646756
This fixes that
=> Fix name resolution for host names in config

tun_android.go, tun_ios.go
Got missed on the global logger removal PR. Will try to get a lightweight compile test going for these too.
=> Fix tun funcs for ios and android

sshd/server.go
@briankelly hit this earlier today, I have been unable to reproduce but the panic doesn't lie.
=> Add locking around ssh conns to avoid concurrent map access on reload

CHANGELOG.md, outside.go
Hi @nbrownus 
Fixed a small bug that was introduced in 
https://github.com/slackhq/nebula/commit/df7c7eec4a39bd0eb73a66a4e9d38e70efae721e#diff-5d05d02296a1953fd5fbcb3f4ab486bc5f7c34b14c3bdedb068008ec8ff5beb4
having problems due to it
=> fixed recv_errors spoofing condition

connection_manager.go, connection_manager_test.go, control.go, control_test.go, dns_server.go, e2e/handshakes_test.go, e2e/helpers_test.go, handshake_manager.go, handshake_manager_test.go, hostmap.go, inside.go, lighthouse.go, outside.go, ssh.go
Builds upon #460 to further normalize vpn ip names
=> Rename vpn ip

README.md
This will add some copy to the README.md about Arch and Fedora Linux distribution packages.
=> Add info about Distribution Packages.

CHANGELOG.md
Update CHANGELOG for Nebula v1.5.0
=> Prepare v1.5.0 release

interface.go, main.go, overlay/device.go, tun_windows.go
=> Start the overlay package with the old Inside interface

control_tester.go, interface.go, overlay/device.go, overlay/route.go, overlay/tun.go, overlay/tun_android.go, overlay/tun_darwin.go, overlay/tun_disabled.go, overlay/tun_freebsd.go, overlay/tun_ios.go, overlay/tun_linux.go, overlay/tun_tester.go, overlay/tun_water_windows.go, overlay/tun_wintun_windows.go, test/tun.go
=> Refactoring more nits out

cmd/nebula-cert/ca.go, cmd/nebula-cert/ca_test.go, cmd/nebula-cert/sign.go, cmd/nebula-cert/sign_test.go
Addresses this comment https://github.com/slackhq/nebula/issues/6#issuecomment-987120712
=> Be more clear about ipv4 in nebula-cert

CHANGELOG.md
Update CHANGELOG for Nebula v1.5.2
=> Prepare v1.5.2

config/config.go, connection_manager_test.go, control.go, handshake.go, handshake_ix.go, handshake_manager_test.go, inside.go, lighthouse.go, lighthouse_test.go, main.go, outside.go, punchy.go, punchy_test.go
Adds support for reloading many of the `lighthouse` and `punchy` config stanzas
Replaces #149
=> Lighthouse reload support

cert.go
=> Remove x509 config loading code

overlay/tun_android.go, overlay/tun_ios.go
#581 broke `unsafe_routes` for ios and android, this fixes them. Actual routes are handled before nebula in both cases, we just need to know the via.
=> Support unsafe_routes on mobile again

CHANGELOG.md
All changes visible in this milestone:
- https://github.com/slackhq/nebula/milestone/9?closed=1
=> Prepare changelog for v1.6.1

README.md, cmd/nebula-service/service.go
=> Use config.yml consistently (not config.yaml)

README.md
=> Nebula is now in Fedora official repositories

dist/arch/nebula.service, dist/fedora/nebula.service, examples/quickstart-vagrant/ansible/roles/nebula/files/systemd.nebula.service, examples/service_scripts/nebula.service
Ensure DNS is running before starting nebula.
Fixes #745. Thanks a lot @JohnMaguire for the suggestion :-)
Closes #792 
Fixes #797
=> Add nss-lookup to the systemd wants

examples/config.yml
=> Update example config with IPv6 note for allow lists

cmd/nebula-cert/main.go, cmd/nebula-cert/main_test.go
=> Add note indicating modes have usage text

cert/cert.go, cert/cert_test.go, cert/errors.go, connection_manager.go
=> Always disconnect block listed hosts

connection_manager.go
@wadey found a possible dead lock with `tryRehandshake` so this moves the attempt outside of the hostmap read lock which avoids the situation.
=> Try rehandshaking a main hostinfo after releasing hostmap read lock

.github/ISSUE_TEMPLATE/config.yml, SECURITY.md
=> add SECURITY.md

README.md
=> Update README to include a link to go install docs

udp/udp_darwin.go
Shutting down a nebula config on iOS started hanging as a result of using `u.File()`
=> Fix rebind to not put the socket in blocking mode

.github/workflows/smoke/build-relay.sh, .github/workflows/smoke/build.sh, .github/workflows/smoke/smoke-relay.sh, .github/workflows/smoke/smoke.sh
Let the host deal with this detail if necessary
=> smoke-test: don't assume docker needs sudo

examples/config.yml
=> Fix truncated comment in config.yml

overlay/route.go, overlay/tun.go, overlay/tun_android.go, overlay/tun_darwin.go, overlay/tun_freebsd.go, overlay/tun_ios.go, overlay/tun_linux.go, overlay/tun_netbsd.go, overlay/tun_openbsd.go, overlay/tun_tester.go, overlay/tun_water_windows.go, overlay/tun_windows.go, overlay/tun_wintun_windows.go
Supports reloading `tun.unsafe_routes`
=> Unsafe route reload

LOGGING.md, examples/config.yml, handshake_ix.go
=> Don't log invalid certificates

dns_server.go
=>  Fix errant capitalisation in DNS TXT response 

noiseutil/nist.go
Quick fix for an error message I ran across while debugging something.
=> minor text fixes

CHANGELOG.md
- Ensure messageCounter is set before handshake is complete. (#1154)
=> prepare CHANGELOG for v1.9.2

CHANGELOG.md
- Initialize messageCounter to 2 instead of verifying later. (#1156)
=> prepare CHANGELOG for v1.9.3

cmd/nebula-cert/ca.go, cmd/nebula-cert/sign.go
It didn't build, now it does. Probably not backwards compatible.
=> make nebula-cert build+function

CHANGELOG.md
Non dependency changes:
- #1194
- #1191
- #1188
- #1185
- #1181
- #1173
- #1171
- #1164
- #1162
=> prepare CHANGELOG for v1.9.4

cert/ca_pool.go, cert/errors.go, cmd/nebula-cert/verify.go, cmd/nebula-cert/verify_test.go
Also added specific handling for `"could not find ca for the certificate"` -- which is an unhelpful message in a world where you have multiple certs probably issued by at least two different CAs
=> [cert-v2] nebula-cert should verify all certs

connection_manager.go, connection_manager_test.go, examples/config.yml, handshake_ix.go, handshake_manager_test.go, interface.go, lighthouse.go, lighthouse_test.go, pki.go
Supersedes #1374 because Github didn't like me having two forks of nebula.
=> Rename pki.default_version to pki.initiating_version

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
Following up on a long overdue to-do item.
You can test the change by clicking "New issue" here: https://github.com/johnmaguire/nebula-test/issues
And by clicking "Create pull request" here: https://github.com/johnmaguire/nebula-test/compare/master...verify-private-key-ca
I had to use a separate repository that left the fork network to test these changes, but the commit should match.
=> Update issue and PR templates

udp/udp_rio_windows.go
We have reports from customers that their Windows Nebula hosts break, failing to tunnel traffic.
Analyzing these customer scenarios, we've learned that sometimes the UDP receive goroutine is no longer running. This results in no tunneled UDP traffic being received by the broken host. We believe the root cause is that the receive function sometimes returns an error, and the wrapping ListenOut function assumes all errors indicate the closure of the UDP socket.
We're still not sure what the cause of the error returns are, but this PR makes the reader more robust to error returns. It immediately returns if the error is net.ErrClosed. For other errors, it will use a rudimentary backoff and eventually fail hard with a panic if the errors don't cease. This is to avoid a fast error loop behavior …
=> Retry UDP receive on Windows in some receive error cases

connection_manager.go
This landed in release-1.9 branch #1403, this PR is for master. 
With the move to ipnet.Addr types, there will be a panic if an uninitialized netip.Addr type has As4() called on it.
We received a stack trace from a user showing this was happening in connection_manager. Based on code inspection, this PR ensures that every State case is covered to avoid calling functions against an uninitialized Addr.
I tried for a bit, but couldn't come up with a nice automated test for this case.
=> Fix relay migration panic by covering every possible relay state

udp/errors.go, udp/udp_darwin.go, udp/udp_generic.go, udp/udp_linux.go
Port of #1426 to the main branch
=> Darwin udp fix

pkclient/pkclient_cgo.go
Specify key length in DeriveNoise
=> Set CKA_VALUE_LEN attribute in DeriveNoise
